using LP.Umbraco.AdvancedPermissions.Core.Models;

namespace LP.Umbraco.AdvancedPermissions.Data.Entities;

/// <summary>
/// Entity Framework Core entity representing a single advanced security permission entry
/// stored in the <c>AdvancedPermission</c> database table.
/// </summary>
public sealed class AdvancedPermissionEntity
{
    /// <summary>
    /// Gets or sets the primary key (GUID, generated by the application).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the key of the content node this permission applies to.
    /// Use <c>AdvancedPermissionsConstants.VirtualRootNodeKey</c> for virtual-root (default) entries
    /// that apply before any explicit node entries.
    /// </summary>
    public Guid NodeKey { get; set; }

    /// <summary>
    /// Gets or sets the alias of the role this permission applies to.
    /// This is either a user group alias or <c>$everyone</c> for the virtual Everyone role.
    /// </summary>
    public string RoleAlias { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the permission verb, e.g. <c>Umb.Document.Read</c>.
    /// </summary>
    public string Verb { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the permission state (Allow or Deny).
    /// </summary>
    public PermissionState State { get; set; }

    /// <summary>
    /// Gets or sets the scope at which this entry applies within the content tree.
    /// </summary>
    public PermissionScope Scope { get; set; }
}
