// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umbraco.Community.AdvancedPermissions.Data.Context;

#nullable disable

namespace Umbraco.Community.AdvancedPermissions.Data.Migrations.SqlServer
{
    [DbContext(typeof(AdvancedPermissionsDbContextSqlServer))]
    [Migration("20260521192835_AddDocTypePermission")]
    partial class AddDocTypePermission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Umbraco.Community.AdvancedPermissions.Data.Entities.AdvancedPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("NodeKey")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NodeKey");

                    b.Property<string>("RoleAlias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RoleAlias");

                    b.Property<int>("Scope")
                        .HasColumnType("int")
                        .HasColumnName("Scope");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("State");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Verb");

                    b.HasKey("Id");

                    b.HasIndex("NodeKey")
                        .HasDatabaseName("IX_AdvancedPermission_NodeKey");

                    b.HasIndex("RoleAlias")
                        .HasDatabaseName("IX_AdvancedPermission_RoleAlias");

                    b.HasIndex("NodeKey", "RoleAlias")
                        .HasDatabaseName("IX_AdvancedPermission_NodeKey_RoleAlias");

                    b.HasIndex("NodeKey", "RoleAlias", "Verb", "Scope")
                        .IsUnique()
                        .HasDatabaseName("IX_AdvancedPermission_Unique");

                    b.ToTable("AdvancedPermission", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.AdvancedPermissions.Data.Entities.DocTypePermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("ContentTypeKey")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ContentTypeKey");

                    b.Property<Guid>("NodeKey")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NodeKey");

                    b.Property<string>("RoleAlias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RoleAlias");

                    b.Property<int>("Scope")
                        .HasColumnType("int")
                        .HasColumnName("Scope");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("State");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Verb");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeKey")
                        .HasDatabaseName("IX_DocTypePermission_ContentTypeKey");

                    b.HasIndex("NodeKey")
                        .HasDatabaseName("IX_DocTypePermission_NodeKey");

                    b.HasIndex("RoleAlias")
                        .HasDatabaseName("IX_DocTypePermission_RoleAlias");

                    b.HasIndex("RoleAlias", "ContentTypeKey", "Verb")
                        .HasDatabaseName("IX_DocTypePermission_RoleAlias_ContentTypeKey_Verb");

                    b.HasIndex("NodeKey", "ContentTypeKey", "RoleAlias", "Verb", "Scope")
                        .IsUnique()
                        .HasDatabaseName("IX_DocTypePermission_Unique");

                    b.ToTable("DocTypePermission", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
