import type { UmbLocalizationDictionary } from '@umbraco-cms/backoffice/localization-api';

export default {
  uap: {
    // ── Navigacija ────────────────────────────────────────────────────────
    sectionLabel: 'Napredne dozvole',
    group_content: 'Dozvole za sadržaj',
    group_documentTypes: 'Dozvole za tip dokumenta',
    group_library: 'Dozvole za Biblioteku',
    group_libraryElementTypes: 'Dozvole za tipove elemenata Biblioteke',
    menuItem_permissionsEditor: 'Uređivač dozvola',
    menuItem_accessViewer: 'Pregled pristupa',
    editorsSectionLabel: 'Urednici',
    viewersSectionLabel: 'Pregledi',
    permissionsEditor: 'Uređivač dozvola za sadržaj',
    accessViewer: 'Pregled pristupa',

    // ── Općenito ──────────────────────────────────────────────────────────
    roleLabel: 'Grupa korisnika',
    rolePlaceholder: '— Odaberite grupu korisnika —',
    userLabel: 'Korisnik',
    saveChanges: 'Spremi promjene',
    discard: 'Odbaci',
    cancel: 'Otkaži',
    apply: 'Primijeni',
    close: 'Zatvori',
    inherit: 'Naslijedi',
    allow: 'Dozvoli',
    deny: 'Zabrani',
    umbracoUsers: 'Svi korisnici',

    // ── Uređivač dozvola ─────────────────────────────────────────────────
    editorHeadline: 'Uređivač dozvola za sadržaj',
    selectRolePrompt: 'Odaberite grupu korisnika iznad za upravljanje njenim dozvolama.',
    permissionsSaved: 'Dozvole spremljene.',
    saveFailed: (error: string) => `Spremanje nije uspjelo: ${error}`,
    contentNodeHeader: 'Čvor sadržaja',
    contentRoot: 'Zadane dozvole',
    expand: 'Proširi',
    collapse: 'Skupi',

    // ── Dijalog dozvola ───────────────────────────────────────────────────
    dialogHeadline: (verb: string, nodeName: string) => `Postavi dozvolu ${verb} za ‘${nodeName}’`,
    descendantsSection: 'Potomci (ako se razlikuju)',
    dialogInstructions: 'Postavite dozvolu za ovaj čvor. Po zadanim postavkama ovo se primjenjuje i na sve potomke. Koristite “Potomci (ako se razlikuju)” da postavite drugačiju dozvolu za podređene čvorove.',
    virtualRootInherit: 'Nije postavljeno (ukloni stavku)',
    virtualRootAllow: 'Dozvoli (sav sadržaj)',
    virtualRootDeny: 'Zabrani (sav sadržaj)',
    dialogResult: 'Rezultat',
    previewBothInherit: 'Nijedna dozvola nije postavljena. Nasljeđuje od nadređenog čvora.',
    previewUniform: (action: string) => `${action} na ovom čvoru i svim potomcima.`,
    previewNodeOnly: (action: string) => `${action} samo na ovom čvoru. Potomci nisu pogođeni ovim pravilom.`,
    previewDescOnly: (action: string) => `Nema eksplicitne dozvole na ovom čvoru. ${action} na svim potomcima.`,
    previewSplit: (nodeAction: string, descAction: string) => `${nodeAction} na ovom čvoru. ${descAction} na svim potomcima.`,
    previewVirtualInherit: 'Nije postavljena zadana dozvola.',
    previewVirtualSet: (action: string) => `${action} po zadanim postavkama za sav sadržaj.`,
    previewPriorityNode: 'Prioritetno nadjačavanje je postavljeno na ovom čvoru.',
    previewPriorityDesc: 'Prioritetno nadjačavanje je postavljeno na potomcima.',
    previewPriorityBoth: 'Prioritetno nadjačavanje je postavljeno.',

    // ── Prioritetno nadjačavanje ──────────────────────────────────────
    priorityOverride: 'Prioritetno nadjačavanje',
    priorityOverrideTooltip: (permission: string, nodeName: string) =>
      `Korisnik može pripadati većem broju grupa korisnika. Uobičajeno, efektivna dozvola slijedi fiksni redoslijed prioriteta. Označavanjem ovog polja taj se redoslijed nadjačava, tako da ovdje odabrana postavka “${permission}” gotovo uvijek postaje rezultat za “${nodeName}”, bez obzira na ostale grupe korisnika. Koristite štedljivo.`,
    priorityOverrideBadgeTitle: 'Prioritetno nadjačavanje je postavljeno na ovoj stavci',
    priorityOverrideWonTitle: 'Razriješeno putem prioritetnog nadjačavanja',
    priorityOverrideSuppressedHeader: 'Prioritetno nadjačavanje je promijenilo rezultat',
    priorityOverrideSuppressedHint: 'Bez njega bi rezultat bio:',

    // ── Pregled pristupa ──────────────────────────────────────────────────
    viewerHeadline: 'Pregled pristupa sadržaju',
    byRole: 'Po grupi korisnika',
    byUser: 'Po korisniku',
    chooseRole: 'Odaberite grupu korisnika',
    chooseUser: 'Odaberite korisnika',
    selectSubjectPrompt: 'Odaberite grupu korisnika ili korisnika za pregled efektivnih dozvola.',
    legendAllow: 'Dozvoli',
    legendDeny: 'Zabrani',
    clickForReasoning: (label: string) => `${label} — kliknite za obrazloženje`,
    subjectOr: 'ili',

    // ── Dijalog za odabir grupe korisnika ─────────────────────────────────
    rolePickerHeadline: 'Odaberite grupu korisnika',
    rolePickerFilter: 'Unesite za filtriranje…',
    rolePickerNoResults: 'Nijedna grupa korisnika ne odgovara filteru.',
    rolePickerNameHeader: 'Grupa korisnika',

    // ── Dijalog za odabir korisnika ───────────────────────────────────────
    userPickerHeadline: 'Odaberite korisnika',
    userPickerFilter: 'Unesite za filtriranje…',
    userPickerNoResults: 'Nijedan korisnik ne odgovara filteru.',
    userPickerNameHeader: 'Korisnik',

    // ── Dijalog obrazloženja ──────────────────────────────────────────────
    reasoningHeadline: (verb: string, nodeName: string) => `Dozvola ${verb} za “${nodeName}”`,
    effectiveAllowed: (subject: string, verb: string, nodeName: string) =>
      `${subject} ima dozvolu ${verb} za “${nodeName}”.`,
    effectiveDenied: (subject: string, verb: string, nodeName: string) =>
      `${subject} nema dozvolu ${verb} za “${nodeName}”.`,
    dialogSecurityHeader: 'Sigurnost',
    defaultPermissions: 'Zadane dozvole',
    determiningEntry: 'Ova stavka ima prednost',
    noReasoningData: 'Nema dostupnih podataka o dozvoli za ovaj glagol.',
    defaultAllowNote: 'Nisu postavljene dozvole, ovo je dozvoljeno po zadanim postavkama.',
    defaultDenyNote: 'Nisu postavljene dozvole, ovo je zabranjeno po zadanim postavkama.',

    // ── Poruka preusmjeravanja granularnih dozvola ────────────────────────
    redirectMessage:
      'Dozvolama za dokumente za ovu grupu korisnika upravlja paket Advanced Permissions. Otvorite Uređivač dozvola za sadržaj u sekciji Korisnici za konfiguraciju dozvola.',

    // ── Dozvole za tipove dokumenata ──────────────────────────────────────
    role: 'Grupa korisnika',
    pickRole: 'Odaberite grupu korisnika',
    user: 'Korisnik',
    pickUser: 'Odaberite korisnika',
    node: 'Čvor',
    pickNode: 'Odaberite čvor',
    state: 'Status',
    scope: 'Opseg',
    scope_thisNodeOnly: 'Samo ovaj čvor',
    scope_thisNodeAndDescendants: 'Ovaj čvor i potomci',
    scope_descendantsOnly: 'Samo potomci',

    docTypePermissions_menuLabel: 'Uređivač dozvola za tip dokumenta',
    docTypePermissions_insertOptionsMenuLabel: 'Pregled opcija umetanja',
    docTypePermissions_workspaceTitle: 'Uređivač dozvola za tip dokumenta',
    docTypePermissions_auditTitle: 'Pregled pristupa tipovima dokumenata',
    docTypePermissions_allDocTypes: 'Svi tipovi dokumenata',
    docTypePermissions_verbInsert: 'Umetni',
    docTypePermissions_documentType: 'Tip dokumenta',
    chooseDocType: 'Odaberite tip dokumenta',
    notAnInsertOption: 'Ovaj tip dokumenta trenutno nije opcija umetanja na ovom čvoru.',
    notAnInsertOptionAllowedNote: 'Ovaj tip dokumenta nije opcija umetanja na ovom čvoru, ali bi inače bio dozvoljen.',
    notAnInsertOptionDeniedNote: 'Ovaj tip dokumenta nije opcija umetanja na ovom čvoru, ali bi inače bio zabranjen.',
    docTypePermissions_pickDocType: '— Odaberite tip dokumenta —',
    docTypePermissions_pickToStart: 'Odaberite grupu korisnika i tip dokumenta za početak.',
    docTypePermissions_defaultRowLabel: 'Zadano (primjenjuje se svuda)',
    docTypePermissions_pendingNodeLabel: '(nespremljeni čvor)',
    docTypePermissions_addScopeNode: 'Dodaj nadjačavanje opsega',
    docTypePermissions_notSet: 'Nije postavljeno',
    docTypePermissions_noResults: 'Nisu pronađeni tipovi dokumenata.',
    docTypePermissions_useRoot: 'Koristi korijen',
    docTypePermissions_pickedNode: 'Čvor:',
    docTypePermissions_rootLevel: 'Korijenski nivo',
    docTypePermissions_reasoning: 'Obrazloženje',
    docTypePermissions_defaultAllow: 'Dozvoljeno po zadanim postavkama',
    docTypePermissions_viaDefault: 'iz zadanog reda',
    // -- i18n completion (machine-translated, pending review) --
    help_contentPermissions_description: 'Upravljajte dozvolama Dozvoli/Zabrani po grupi korisnika kroz vaše stablo sadržaja.',
    help_accessViewer_description: 'Pogledajte efektivne dozvole koje korisnik ili grupa ima na bilo kojem čvoru, s potpunim obrazloženjem.',
    help_docTypePermissions_description: 'Odredite koje tipove dokumenata svaka grupa korisnika može kreirati i gdje.',
    help_insertOptions_description: 'Provjerite koje tipove dokumenata korisnik ili grupa korisnika može kreirati na svakom čvoru.',
    help_libraryPermissions_description: 'Upravljajte dozvolama Dozvoli/Zabrani po grupi korisnika kroz stablo Biblioteke.',
    help_elementTypePermissions_description: 'Kontrolišite koje tipove elemenata svaka grupa korisnika može koristiti u Biblioteci.',
    help_libraryAccessViewer_description: 'Pogledajte efektivne dozvole Biblioteke koje korisnik ili grupa korisnika ima na svakom čvoru.',
    help_libraryInsertViewer_description: 'Provjerite koje tipove elemenata korisnik ili grupa korisnika može umetnuti u Biblioteku.',
    help_learnMore: 'Saznajte više',
    help_modalTitle: 'Pomoć',
    help_tabAbout: 'O ovoj stranici',
    help_tabConcepts: 'Koncepti',
    help_concept_scope_tip: 'Opseg kontroliše koliko daleko pravilo doseže: ovaj čvor, ovaj čvor i njegovi potomci, ili samo potomci.',
    help_concept_priorityOverride_tip: 'Prioritetno nadjačavanje prisiljava ovu stavku da pobijedi nad uobičajenim redoslijedom razrješavanja.',
    help_concept_allowDeny_tip: 'Dozvoli odobrava dozvolu, Zabrani je opoziva, a ostavljanje nepostavljenim nasljeđuje od najbližeg pretka.',
    help_concept_reasoning_tip: 'Kliknite na bilo koju ćeliju da vidite tačno kako je dozvola razriješena.',
    previewElementFolderSet: (action: string) => `Ne primjenjuje se na ovaj folder. ${action} na elementima unutar njega.`,
    previewElementFolderInherit: 'Ne primjenjuje se na ovaj folder. Elementi unutar njega nasljeđuju od svog nadređenog čvora.',
    dialogElementFolderNote: (verb: string) => `“${verb}” se ne primjenjuje na folder — samo na elemente unutar njega.`,
    elementFolderDescSection: 'Elementi unutar',
    naChip: 'N/D',
    redirectMessageElement:
      'Dozvolama za Biblioteku (elemente) za ovu grupu korisnika upravlja paket Advanced Permissions. Otvorite Uređivač dozvola za Biblioteku u sekciji Korisnici za konfiguraciju dozvola.',
    library_menuLabel: 'Uređivač dozvola za Biblioteku',
    library_editorHeadline: 'Uređivač dozvola za Biblioteku',
    library_accessViewerMenuLabel: 'Pregled pristupa Biblioteci',
    library_accessViewerHeadline: 'Pregled pristupa Biblioteci',
    library_nodeHeader: 'Stavka Biblioteke',
    library_root: 'Zadane dozvole',
    library_selectRolePrompt: 'Odaberite grupu korisnika za upravljanje njenim dozvolama za Biblioteku.',
    library_permissionsSaved: 'Dozvole za Biblioteku spremljene.',
    library_notApplicableTitle: (verb: string) => `${verb} se ne primjenjuje na foldere — i dalje se može postaviti za stavke unutar njih.`,
    library_folderInheritLabel: 'Stavke unutar (potomci)',
    libraryInsertViewer_menuLabel: 'Pregled umetanja u Biblioteku',
    libraryInsertViewer_headline: 'Pregled pristupa tipovima elemenata Biblioteke',
    libraryInsertViewer_intro: 'Prikazuje koje tipove elemenata Biblioteke grupa korisnika ili korisnik može kreirati, razriješeno kroz sve njihove grupe. Kliknite na red da vidite obrazloženje.',
    elementTypePermissions_menuLabel: 'Dozvole za tipove elemenata Biblioteke',
    elementTypePermissions_headline: 'Uređivač dozvola za tipove elemenata Biblioteke',
    elementTypePermissions_intro: 'Kontrolišite koje tipove elemenata svaka grupa korisnika može kreirati u Biblioteci. Tipovi elemenata su po zadanim postavkama dostupni za kreiranje; postavite Dozvoli ili Zabrani — uz opcionalno prioritetno nadjačavanje — da kontrolišete kako se izbor razrješava kada korisnik pripada većem broju grupa.',
    elementTypePermissions_typeHeader: 'Tip elementa',
    elementTypePermissions_verbCreate: 'Kreiraj u Biblioteci',
    elementTypePermissions_noTypes: 'Nisu pronađeni tipovi elemenata Biblioteke. Označite tip dokumenta kao tip elementa i omogućite “Dozvoli u Biblioteci”.',
    elementType_dialogHeadline: (type: string) => `Dozvola za kreiranje za ‘${type}’ u Biblioteci`,
    elementType_inheritLabel: 'Nije postavljeno (dozvoljeno po zadanim postavkama)',
    elementType_allowLabel: 'Dozvoli (može se kreirati u Biblioteci)',
    elementType_denyLabel: 'Zabrani (skriveno iz Biblioteke)',
    elementType_previewInherit: 'Nema eksplicitnog pravila. Ovaj tip elementa se po zadanim postavkama može kreirati u Biblioteci.',
    elementType_previewSet: (action: string) => `${action} kreiranje ovog tipa elementa u Biblioteci.`,
  },
} satisfies UmbLocalizationDictionary;
