import type { UmbLocalizationDictionary } from '@umbraco-cms/backoffice/localization-api';

export default {
  uap: {
    // ── Navigation ────────────────────────────────────────────────────────
    sectionLabel: 'Avancerede tilladelser',
    editorsSectionLabel: 'Redaktører',
    viewersSectionLabel: 'Visninger',
    permissionsEditor: 'Editor til indholdstilladelser',
    accessViewer: 'Adgangsvisning',

    // ── Almindeligt ───────────────────────────────────────────────────────
    roleLabel: 'Brugergruppe',
    rolePlaceholder: '— Vælg en brugergruppe —',
    userLabel: 'Bruger',
    saveChanges: 'Gem ændringer',
    discard: 'Kassér',
    cancel: 'Fortryd',
    apply: 'Anvend',
    close: 'Luk',
    inherit: 'Nedarv',
    allow: 'Tillad',
    deny: 'Nægt',
    umbracoUsers: 'Alle brugere',

    // ── Tilladelseseditor ─────────────────────────────────────────────────
    editorHeadline: 'Editor til indholdstilladelser',
    selectRolePrompt: 'Vælg en brugergruppe ovenfor for at administrere dens tilladelser.',
    permissionsSaved: 'Tilladelser gemt.',
    saveFailed: (error: string) => `Gem mislykkedes: ${error}`,
    contentNodeHeader: 'Indholdsnode',
    contentRoot: 'Standardtilladelser',
    expand: 'Fold ud',
    collapse: 'Fold sammen',

    // ── Tilladelsesdialog ─────────────────────────────────────────────────
    dialogHeadline: (verb: string, nodeName: string) => `Indstil ${verb}-tilladelse for ‘${nodeName}’`,
    descendantsSection: 'Undernoder (hvis afvigende)',
    dialogInstructions: 'Indstil tilladelsen for denne node. Som standard gælder dette også for alle undernoder. Brug “Undernoder (hvis afvigende)” til at indstille en anden tilladelse for undernoder.',
    virtualRootInherit: 'Ikke indstillet (fjern post)',
    virtualRootAllow: 'Tillad (alt indhold)',
    virtualRootDeny: 'Nægt (alt indhold)',
    dialogResult: 'Resultat',
    previewBothInherit: 'Ingen tilladelse indstillet. Nedarves fra overordnet node.',
    previewUniform: (action: string) => `${action} på denne node og alle undernoder.`,
    previewNodeOnly: (action: string) => `${action} kun på denne node. Undernoder påvirkes ikke af denne regel.`,
    previewDescOnly: (action: string) => `Ingen eksplicit tilladelse på denne node. ${action} på alle undernoder.`,
    previewSplit: (nodeAction: string, descAction: string) => `${nodeAction} på denne node. ${descAction} på alle undernoder.`,
    previewVirtualInherit: 'Ingen standardtilladelse indstillet.',
    previewVirtualSet: (action: string) => `${action} som standard for alt indhold.`,
    previewPriorityNode: 'Prioritetstilsidesættelse er angivet på denne node.',
    previewPriorityDesc: 'Prioritetstilsidesættelse er angivet på undernoder.',
    previewPriorityBoth: 'Prioritetstilsidesættelse er angivet.',

    // ── Prioritetstilsidesættelse ─────────────────────────────────────
    priorityOverride: 'Prioritetstilsidesættelse',
    priorityOverrideTooltip: (permission: string, nodeName: string) =>
      `En bruger kan tilhøre flere brugergrupper. Normalt følger den effektive tilladelse en fast prioritetsrækkefølge. Ved at markere dette felt tilsidesættes den rækkefølge, så den “${permission}”-indstilling, du vælger her, næsten altid bliver resultatet for “${nodeName}”, uanset brugerens øvrige grupper. Bruges med omtanke.`,
    priorityOverrideBadgeTitle: 'Prioritetstilsidesættelse er angivet på denne post',
    priorityOverrideWonTitle: 'Løst via prioritetstilsidesættelse',
    priorityOverrideSuppressedHeader: 'Prioritetstilsidesættelse ændrede resultatet',
    priorityOverrideSuppressedHint: 'Uden den ville resultatet have været:',

    // ── Adgangsvisning ────────────────────────────────────────────────────
    viewerHeadline: 'Adgangsvisning',
    byRole: 'Efter brugergruppe',
    byUser: 'Efter bruger',
    chooseRole: 'Vælg brugergruppe',
    chooseUser: 'Vælg bruger',
    selectSubjectPrompt: 'Vælg en brugergruppe eller bruger for at se de effektive tilladelser.',
    legendAllow: 'Tillad',
    legendDeny: 'Nægt',
    clickForReasoning: (label: string) => `${label} — klik for begrundelse`,
    subjectOr: 'eller',

    // ── Brugergruppevælger-dialog ─────────────────────────────────────────
    rolePickerHeadline: 'Vælg en brugergruppe',
    rolePickerFilter: 'Skriv for at filtrere…',
    rolePickerNoResults: 'Ingen brugergrupper matcher filteret.',
    rolePickerNameHeader: 'Brugergruppe',

    // ── Brugervælger-dialog ───────────────────────────────────────────────
    userPickerHeadline: 'Vælg en bruger',
    userPickerFilter: 'Skriv for at filtrere…',
    userPickerNoResults: 'Ingen brugere matcher filteret.',
    userPickerNameHeader: 'Bruger',

    // ── Begrundelsesdialog ────────────────────────────────────────────────
    reasoningHeadline: (verb: string, nodeName: string) => `${verb}-tilladelse for “${nodeName}”`,
    effectiveAllowed: (subject: string, verb: string, nodeName: string) =>
      `${subject} er blevet tilladt ${verb}-tilladelse for “${nodeName}”.`,
    effectiveDenied: (subject: string, verb: string, nodeName: string) =>
      `${subject} er blevet nægtet ${verb}-tilladelse for “${nodeName}”.`,
    dialogSecurityHeader: 'Sikkerhed',
    defaultPermissions: 'Standardtilladelser',
    determiningEntry: 'Denne post har forrang',
    noReasoningData: 'Ingen tilladelsesdata tilgængelige for dette verbum.',
    defaultAllowNote: 'Der er ikke indstillet nogen tilladelser, dette er tilladt som standard.',
    defaultDenyNote: 'Der er ikke indstillet nogen tilladelser, dette nægtes som standard.',

    // ── Omdirigeringsbesked for granulære tilladelser ─────────────────────
    redirectMessage:
      'Dokumenttilladelser for denne brugergruppe administreres af Advanced Permissions-pakken. Åbn Tilladelseseditoren i sektionen Brugere for at konfigurere tilladelser.',

    // ── Dokumenttype-tilladelser ──────────────────────────────────────────
    role: 'Brugergruppe',
    pickRole: 'Vælg brugergruppe',
    user: 'Bruger',
    pickUser: 'Vælg bruger',
    node: 'Node',
    pickNode: 'Vælg node',
    state: 'Status',
    scope: 'Omfang',
    scope_thisNodeOnly: 'Kun denne node',
    scope_thisNodeAndDescendants: 'Denne node og undernoder',
    scope_descendantsOnly: 'Kun undernoder',

    docTypePermissions_menuLabel: 'Editor til dokumenttype-tilladelser',
    docTypePermissions_insertOptionsMenuLabel: 'Visning af indsætningsmuligheder',
    docTypePermissions_workspaceTitle: 'Editor til dokumenttype-tilladelser',
    docTypePermissions_auditTitle: 'Visning af indsætningsmuligheder',
    docTypePermissions_allDocTypes: 'Alle dokumenttyper',
    docTypePermissions_verbInsert: 'Indsæt',
    docTypePermissions_documentType: 'Dokumenttype',
    chooseDocType: 'Vælg dokumenttype',
    notAnInsertOption: 'Denne dokumenttype er i øjeblikket ikke en indsætningsmulighed på denne node.',
    notAnInsertOptionAllowedNote: 'Denne dokumenttype er ikke en indsætningsmulighed på denne node, men ville ellers være tilladt.',
    notAnInsertOptionDeniedNote: 'Denne dokumenttype er ikke en indsætningsmulighed på denne node, men ville ellers blive nægtet.',
    docTypePermissions_pickDocType: '— Vælg en dokumenttype —',
    docTypePermissions_pickToStart: 'Vælg en brugergruppe og dokumenttype for at begynde.',
    docTypePermissions_defaultRowLabel: 'Standard (gælder overalt)',
    docTypePermissions_pendingNodeLabel: '(ikke-gemt node)',
    docTypePermissions_addScopeNode: 'Tilføj omfangstilsidesættelse',
    docTypePermissions_notSet: 'Ikke indstillet',
    docTypePermissions_noResults: 'Ingen dokumenttyper fundet.',
    docTypePermissions_useRoot: 'Brug rod',
    docTypePermissions_pickedNode: 'Node:',
    docTypePermissions_rootLevel: 'Rodniveau',
    docTypePermissions_reasoning: 'Begrundelse',
    docTypePermissions_defaultAllow: 'Tilladt som standard',
    docTypePermissions_viaDefault: 'fra standardrække',
    // -- i18n completion (machine-translated, pending review) --
    help_contentPermissions_description: 'Administrér Tillad/Nægt-tilladelser pr. brugergruppe på tværs af dit indholdstræ.',
    help_accessViewer_description: 'Se de effektive tilladelser, en bruger eller gruppe har på en hvilken som helst node, med fuld begrundelse.',
    help_docTypePermissions_description: 'Bestem, hvilke dokumenttyper hver brugergruppe kan oprette, og hvor.',
    help_insertOptions_description: 'Gennemgå, hvilke dokumenttyper en bruger eller brugergruppe kan oprette på hver node.',
    help_libraryPermissions_description: 'Administrér Tillad/Nægt-tilladelser pr. brugergruppe på tværs af Library-træet.',
    help_elementTypePermissions_description: 'Styr, hvilke elementtyper hver brugergruppe kan bruge i Library.',
    help_libraryAccessViewer_description: 'Se de effektive Library-tilladelser, en bruger eller brugergruppe har på hver node.',
    help_libraryInsertViewer_description: 'Gennemgå, hvilke elementtyper en bruger eller brugergruppe kan indsætte i Library.',
    help_learnMore: 'Læs mere',
    help_modalTitle: 'Hjælp',
    help_tabAbout: 'Om denne side',
    help_tabConcepts: 'Begreber',
    help_concept_scope_tip: 'Omfang styrer, hvor langt en regel rækker: denne node, denne node og dens undernoder, eller kun undernoder.',
    help_concept_priorityOverride_tip: 'Prioritetstilsidesættelse tvinger denne post til at vinde over den normale opløsningsrækkefølge.',
    help_concept_allowDeny_tip: 'Tillad giver tilladelsen, Nægt fjerner den, og hvis den ikke er angivet, nedarves den fra den nærmeste overordnede node.',
    help_concept_reasoning_tip: 'Klik på en celle for at se nøjagtigt, hvordan tilladelsen blev løst.',
    previewElementFolderSet: (action: string) => `Gælder ikke for denne mappe. ${action} på elementerne i den.`,
    previewElementFolderInherit: 'Gælder ikke for denne mappe. Elementerne i den nedarves fra deres overordnede node.',
    dialogElementFolderNote: (verb: string) => `“${verb}” gælder ikke for en mappe — kun for elementerne i den.`,
    elementFolderDescSection: 'Elementer indeni',
    naChip: 'I/A',
    redirectMessageElement:
      'Library-tilladelser (element) for denne brugergruppe administreres af Advanced Permissions-pakken. Åbn Library-tilladelseseditoren i sektionen Brugere for at konfigurere tilladelser.',
    library_menuLabel: 'Library-tilladelseseditor',
    library_editorHeadline: 'Library-tilladelseseditor',
    library_accessViewerMenuLabel: 'Library-adgangsvisning',
    library_accessViewerHeadline: 'Library-adgangsvisning',
    library_nodeHeader: 'Library-element',
    library_root: 'Standardtilladelser',
    library_selectRolePrompt: 'Vælg en brugergruppe for at administrere dens library-tilladelser.',
    library_permissionsSaved: 'Library-tilladelser gemt.',
    library_notApplicableTitle: (verb: string) => `${verb} gælder ikke for mapper — det kan stadig angives for elementerne indeni.`,
    library_folderInheritLabel: 'Elementer indeni (undernoder)',
    libraryInsertViewer_menuLabel: 'Library-indsætningsvisning',
    libraryInsertViewer_headline: 'Library-indsætningsvisning',
    libraryInsertViewer_intro: 'Viser, hvilke library-elementtyper en brugergruppe eller bruger må oprette, løst på tværs af alle deres grupper. Klik på en række for at se begrundelsen.',
    elementTypePermissions_menuLabel: 'Library-elementtype-tilladelser',
    elementTypePermissions_headline: 'Library-elementtype-tilladelser',
    elementTypePermissions_intro: 'Styr, hvilke elementtyper hver brugergruppe må oprette i Library. Elementtyper kan oprettes som standard; angiv Tillad eller Nægt — med en valgfri prioritetstilsidesættelse — for at styre, hvordan valget løses, når en bruger tilhører flere grupper.',
    elementTypePermissions_typeHeader: 'Elementtype',
    elementTypePermissions_verbCreate: 'Opret i Library',
    elementTypePermissions_noTypes: 'Ingen library-elementtyper fundet. Markér en dokumenttype som elementtype, og aktivér “Tillad i Library”.',
    elementType_dialogHeadline: (type: string) => `Opret-tilladelse for ‘${type}’ i Library`,
    elementType_inheritLabel: 'Ikke indstillet (tilladt som standard)',
    elementType_allowLabel: 'Tillad (kan oprettes i Library)',
    elementType_denyLabel: 'Nægt (skjult fra Library)',
    elementType_previewInherit: 'Ingen eksplicit regel. Denne elementtype kan oprettes i Library som standard.',
    elementType_previewSet: (action: string) => `${action} oprettelse af denne elementtype i Library.`,
  },
} satisfies UmbLocalizationDictionary;
