import type { UmbLocalizationDictionary } from '@umbraco-cms/backoffice/localization-api';

export default {
  uap: {
    // ── ניווט ─────────────────────────────────────────────────────────────
    sectionLabel: 'הרשאות מתקדמות',
    editorsSectionLabel: 'עורכים',
    viewersSectionLabel: 'מציגים',
    permissionsEditor: 'עורך הרשאות תוכן',
    accessViewer: 'מציג גישה',

    // ── כללי ──────────────────────────────────────────────────────────────
    roleLabel: 'קבוצת משתמשים',
    rolePlaceholder: '— בחר קבוצת משתמשים —',
    userLabel: 'משתמש',
    saveChanges: 'שמור שינויים',
    discard: 'בטל שינויים',
    cancel: 'בטל',
    apply: 'החל',
    close: 'סגור',
    inherit: 'ירושה',
    allow: 'אפשר',
    deny: 'מנע',
    umbracoUsers: 'כל המשתמשים',

    // ── עורך ההרשאות ──────────────────────────────────────────────────────
    editorHeadline: 'עורך הרשאות תוכן',
    selectRolePrompt: 'בחר קבוצת משתמשים למעלה כדי לנהל את ההרשאות שלה.',
    permissionsSaved: 'ההרשאות נשמרו.',
    saveFailed: (error: string) => `השמירה נכשלה: ${error}`,
    contentNodeHeader: 'צומת תוכן',
    contentRoot: 'הרשאות ברירת מחדל',
    expand: 'הרחב',
    collapse: 'כווץ',

    // ── תיבת דו-שיח להרשאות ───────────────────────────────────────────────
    dialogHeadline: (verb: string, nodeName: string) => `הגדר הרשאת ${verb} עבור ‘${nodeName}’`,
    descendantsSection: 'צאצאים (אם שונה)',
    dialogInstructions: 'הגדר את ההרשאה לצומת זה. כברירת מחדל, היא חלה גם על כל הצאצאים. השתמש ב“צאצאים (אם שונה)” כדי להגדיר הרשאה שונה לצמתים צאצאים.',
    virtualRootInherit: 'לא מוגדר (הסר ערך)',
    virtualRootAllow: 'אפשר (כל התוכן)',
    virtualRootDeny: 'מנע (כל התוכן)',
    dialogResult: 'תוצאה',
    previewBothInherit: 'לא הוגדרה הרשאה. יורשת מהצומת ההורה.',
    previewUniform: (action: string) => `${action} בצומת זה ובכל הצאצאים.`,
    previewNodeOnly: (action: string) => `${action} בצומת זה בלבד. הצאצאים אינם מושפעים מכלל זה.`,
    previewDescOnly: (action: string) => `אין הרשאה מפורשת בצומת זה. ${action} בכל הצאצאים.`,
    previewSplit: (nodeAction: string, descAction: string) => `${nodeAction} בצומת זה. ${descAction} בכל הצאצאים.`,
    previewVirtualInherit: 'לא הוגדרה הרשאת ברירת מחדל.',
    previewVirtualSet: (action: string) => `${action} כברירת מחדל עבור כל התוכן.`,
    previewPriorityNode: 'עקיפת עדיפות מוגדרת בצומת זה.',
    previewPriorityDesc: 'עקיפת עדיפות מוגדרת בצאצאים.',
    previewPriorityBoth: 'עקיפת עדיפות מוגדרת.',

    // ── עקיפת עדיפות ──────────────────────────────────────────────────────
    priorityOverride: 'עקיפת עדיפות',
    priorityOverrideTooltip: (permission: string, nodeName: string) =>
      `משתמש יכול להשתייך למספר קבוצות משתמשים. בדרך כלל, ההרשאה האפקטיבית עוקבת אחר סדר עדיפות קבוע. סימון תיבה זו עוקף את הסדר הזה, כך שההגדרה “${permission}” שתבחר כאן כמעט תמיד הופכת לתוצאה עבור “${nodeName}”, ללא קשר לקבוצות האחרות של המשתמש. השתמש במשורה.`,
    priorityOverrideBadgeTitle: 'עקיפת עדיפות מוגדרת בערך זה',
    priorityOverrideWonTitle: 'נקבע באמצעות עקיפת עדיפות',
    priorityOverrideSuppressedHeader: 'עקיפת העדיפות שינתה את התוצאה',
    priorityOverrideSuppressedHint: 'בלעדיה, התוצאה הייתה:',

    // ── מציג הגישה ────────────────────────────────────────────────────────
    viewerHeadline: 'מציג גישה',
    byRole: 'לפי קבוצת משתמשים',
    byUser: 'לפי משתמש',
    chooseRole: 'בחר קבוצת משתמשים',
    chooseUser: 'בחר משתמש',
    selectSubjectPrompt: 'בחר קבוצת משתמשים או משתמש כדי להציג את ההרשאות האפקטיביות.',
    legendAllow: 'אפשר',
    legendDeny: 'מנע',
    clickForReasoning: (label: string) => `${label} — לחץ להנמקה`,
    subjectOr: 'או',

    // ── תיבת בחירת קבוצת משתמשים ──────────────────────────────────────────
    rolePickerHeadline: 'בחר קבוצת משתמשים',
    rolePickerFilter: 'הקלד כדי לסנן…',
    rolePickerNoResults: 'אין קבוצות משתמשים התואמות לסינון.',
    rolePickerNameHeader: 'קבוצת משתמשים',

    // ── תיבת בחירת משתמש ──────────────────────────────────────────────────
    userPickerHeadline: 'בחר משתמש',
    userPickerFilter: 'הקלד כדי לסנן…',
    userPickerNoResults: 'אין משתמשים התואמים לסינון.',
    userPickerNameHeader: 'משתמש',

    // ── תיבת דו-שיח להנמקה ────────────────────────────────────────────────
    reasoningHeadline: (verb: string, nodeName: string) => `הרשאת ${verb} עבור “${nodeName}”`,
    effectiveAllowed: (subject: string, verb: string, nodeName: string) =>
      `ל${subject} ניתנה הרשאת ${verb} עבור “${nodeName}”.`,
    effectiveDenied: (subject: string, verb: string, nodeName: string) =>
      `ל${subject} נמנעה הרשאת ${verb} עבור “${nodeName}”.`,
    dialogSecurityHeader: 'אבטחה',
    defaultPermissions: 'הרשאות ברירת מחדל',
    determiningEntry: 'ערך זה גובר',
    noReasoningData: 'אין נתוני הרשאה זמינים עבור פעולה זו.',
    defaultAllowNote: 'לא הוגדרו הרשאות, פעולה זו מותרת כברירת מחדל.',
    defaultDenyNote: 'לא הוגדרו הרשאות, פעולה זו נמנעת כברירת מחדל.',

    // ── הודעת הפניה להרשאות מפורטות ───────────────────────────────────────
    redirectMessage:
      'הרשאות מסמכים עבור קבוצת משתמשים זו מנוהלות על ידי חבילת Advanced Permissions. פתח את עורך ההרשאות במקטע המשתמשים כדי להגדיר הרשאות.',

    // ── הרשאות סוג מסמך ───────────────────────────────────────────────────
    role: 'קבוצת משתמשים',
    pickRole: 'בחר קבוצת משתמשים',
    user: 'משתמש',
    pickUser: 'בחר משתמש',
    node: 'צומת',
    pickNode: 'בחר צומת',
    state: 'מצב',
    scope: 'היקף',
    scope_thisNodeOnly: 'צומת זה בלבד',
    scope_thisNodeAndDescendants: 'צומת זה והצאצאים',
    scope_descendantsOnly: 'צאצאים בלבד',

    docTypePermissions_menuLabel: 'עורך הרשאות סוג מסמך',
    docTypePermissions_insertOptionsMenuLabel: 'מציג אפשרויות הוספה',
    docTypePermissions_workspaceTitle: 'עורך הרשאות סוג מסמך',
    docTypePermissions_auditTitle: 'מציג אפשרויות הוספה',
    docTypePermissions_allDocTypes: 'כל סוגי המסמכים',
    docTypePermissions_verbInsert: 'הוסף',
    docTypePermissions_documentType: 'סוג מסמך',
    chooseDocType: 'בחר סוג מסמך',
    notAnInsertOption: 'סוג מסמך זה אינו כרגע אפשרות הוספה בצומת זה.',
    notAnInsertOptionAllowedNote: 'סוג מסמך זה אינו אפשרות הוספה בצומת זה, אך אחרת הוא היה מותר.',
    notAnInsertOptionDeniedNote: 'סוג מסמך זה אינו אפשרות הוספה בצומת זה, אך אחרת הוא היה נמנע.',
    docTypePermissions_pickDocType: '— בחר סוג מסמך —',
    docTypePermissions_pickToStart: 'בחר קבוצת משתמשים וסוג מסמך כדי להתחיל.',
    docTypePermissions_defaultRowLabel: 'ברירת מחדל (חל בכל מקום)',
    docTypePermissions_pendingNodeLabel: '(צומת לא שמור)',
    docTypePermissions_addScopeNode: 'הוסף עקיפת היקף',
    docTypePermissions_notSet: 'לא מוגדר',
    docTypePermissions_noResults: 'לא נמצאו סוגי מסמכים.',
    docTypePermissions_useRoot: 'השתמש בשורש',
    docTypePermissions_pickedNode: 'צומת:',
    docTypePermissions_rootLevel: 'רמת שורש',
    docTypePermissions_reasoning: 'הנמקה',
    docTypePermissions_defaultAllow: 'מותר כברירת מחדל',
    docTypePermissions_viaDefault: 'משורת ברירת המחדל',
    // -- i18n completion (machine-translated, pending review) --
    help_contentPermissions_description: 'נהל הרשאות אפשר/מנע לכל קבוצת משתמשים על פני עץ התוכן שלך.',
    help_accessViewer_description: 'ראה את ההרשאות האפקטיביות של משתמש או קבוצה בכל צומת, עם הנמקה מלאה.',
    help_docTypePermissions_description: 'החלט אילו סוגי מסמכים כל קבוצת משתמשים יכולה ליצור, והיכן.',
    help_insertOptions_description: 'בדוק אילו סוגי מסמכים משתמש או קבוצת משתמשים יכולים ליצור בכל צומת.',
    help_libraryPermissions_description: 'נהל הרשאות אפשר/מנע לכל קבוצת משתמשים על פני עץ הספרייה.',
    help_elementTypePermissions_description: 'שלוט אילו סוגי רכיבים כל קבוצת משתמשים יכולה להשתמש בספרייה.',
    help_libraryAccessViewer_description: 'ראה את הרשאות הספרייה האפקטיביות של משתמש או קבוצת משתמשים בכל צומת.',
    help_libraryInsertViewer_description: 'בדוק אילו סוגי רכיבים משתמש או קבוצת משתמשים יכולים להוסיף בספרייה.',
    help_learnMore: 'למידע נוסף',
    help_modalTitle: 'עזרה',
    help_tabAbout: 'אודות עמוד זה',
    help_tabConcepts: 'מושגים',
    help_concept_scope_tip: 'היקף קובע עד כמה רחוק מגיע כלל: צומת זה, צומת זה והצאצאים שלו, או צאצאים בלבד.',
    help_concept_priorityOverride_tip: 'עקיפת עדיפות מאלצת ערך זה לגבור על סדר ההכרעה הרגיל.',
    help_concept_allowDeny_tip: 'אפשר מעניק את ההרשאה, מנע שולל אותה, והשארתה לא מוגדרת יורשת מהאב הקדמון הקרוב ביותר.',
    help_concept_reasoning_tip: 'לחץ על כל תא כדי לראות בדיוק כיצד ההרשאה הוכרעה.',
    previewElementFolderSet: (action: string) => `אינו חל על תיקייה זו. ${action} על הרכיבים שבתוכה.`,
    previewElementFolderInherit: 'אינו חל על תיקייה זו. הרכיבים שבתוכה יורשים מההורה שלהם.',
    dialogElementFolderNote: (verb: string) => `“${verb}” אינו חל על תיקייה — רק על הרכיבים שבתוכה.`,
    elementFolderDescSection: 'רכיבים בפנים',
    naChip: 'לא רלוונטי',
    redirectMessageElement:
      'הרשאות ספרייה (רכיב) עבור קבוצת משתמשים זו מנוהלות על ידי חבילת Advanced Permissions. פתח את עורך הרשאות הספרייה במקטע המשתמשים כדי להגדיר הרשאות.',
    library_menuLabel: 'עורך הרשאות ספרייה',
    library_editorHeadline: 'עורך הרשאות ספרייה',
    library_accessViewerMenuLabel: 'מציג גישת ספרייה',
    library_accessViewerHeadline: 'מציג גישת ספרייה',
    library_nodeHeader: 'פריט ספרייה',
    library_root: 'הרשאות ברירת מחדל',
    library_selectRolePrompt: 'בחר קבוצת משתמשים כדי לנהל את הרשאות הספרייה שלה.',
    library_permissionsSaved: 'הרשאות הספרייה נשמרו.',
    library_notApplicableTitle: (verb: string) => `${verb} אינו חל על תיקיות — עדיין ניתן להגדירו עבור הפריטים שבתוכן.`,
    library_folderInheritLabel: 'פריטים בפנים (צאצאים)',
    libraryInsertViewer_menuLabel: 'מציג הוספת ספרייה',
    libraryInsertViewer_headline: 'מציג הוספת ספרייה',
    libraryInsertViewer_intro: 'מציג אילו סוגי רכיבי ספרייה קבוצת משתמשים או משתמש רשאים ליצור, מוכרע על פני כל הקבוצות שלהם. לחץ על שורה כדי לראות את ההנמקה.',
    elementTypePermissions_menuLabel: 'הרשאות סוג רכיב ספרייה',
    elementTypePermissions_headline: 'הרשאות סוג רכיב ספרייה',
    elementTypePermissions_intro: 'שלוט אילו סוגי רכיבים כל קבוצת משתמשים רשאית ליצור בספרייה. סוגי רכיבים ניתנים ליצירה כברירת מחדל; הגדר אפשר או מנע — עם עקיפת עדיפות אופציונלית — כדי לשלוט כיצד הבחירה מוכרעת כאשר משתמש משתייך למספר קבוצות.',
    elementTypePermissions_typeHeader: 'סוג רכיב',
    elementTypePermissions_verbCreate: 'צור בספרייה',
    elementTypePermissions_noTypes: 'לא נמצאו סוגי רכיבי ספרייה. סמן סוג מסמך כסוג רכיב והפעל “אפשר בספרייה”.',
    elementType_dialogHeadline: (type: string) => `הרשאת יצירה עבור ‘${type}’ בספרייה`,
    elementType_inheritLabel: 'לא מוגדר (מותר כברירת מחדל)',
    elementType_allowLabel: 'אפשר (ניתן ליצירה בספרייה)',
    elementType_denyLabel: 'מנע (מוסתר מהספרייה)',
    elementType_previewInherit: 'אין כלל מפורש. סוג רכיב זה ניתן ליצירה בספרייה כברירת מחדל.',
    elementType_previewSet: (action: string) => `${action} יצירת סוג רכיב זה בספרייה.`,
  },
} satisfies UmbLocalizationDictionary;
