import type { UmbLocalizationDictionary } from '@umbraco-cms/backoffice/localization-api';

export default {
  uap: {
    // ── Navigacija ────────────────────────────────────────────────────────
    sectionLabel: 'Napredne dozvole',
    editorsSectionLabel: 'Uređivači',
    viewersSectionLabel: 'Prikazi',
    permissionsEditor: 'Uređivač dozvola sadržaja',
    accessViewer: 'Prikaz pristupa',

    // ── Općenito ──────────────────────────────────────────────────────────
    roleLabel: 'Grupa korisnika',
    rolePlaceholder: '— Odaberite grupu korisnika —',
    userLabel: 'Korisnik',
    saveChanges: 'Spremi promjene',
    discard: 'Otkaži',
    cancel: 'Odustani',
    apply: 'Primijeni',
    close: 'Zatvori',
    inherit: 'Naslijedi',
    allow: 'Dozvoli',
    deny: 'Zabrani',
    umbracoUsers: 'Svi korisnici',

    // ── Uređivač dozvola ─────────────────────────────────────────────────
    editorHeadline: 'Uređivač dozvola sadržaja',
    selectRolePrompt: 'Odaberite grupu korisnika iznad kako biste upravljali njezinim dozvolama.',
    permissionsSaved: 'Dozvole su spremljene.',
    saveFailed: (error: string) => `Spremanje nije uspjelo: ${error}`,
    contentNodeHeader: 'Čvor sadržaja',
    contentRoot: 'Zadane dozvole',
    expand: 'Proširi',
    collapse: 'Sažmi',

    // ── Dijalog dozvola ───────────────────────────────────────────────────
    dialogHeadline: (verb: string, nodeName: string) => `Postavi dozvolu „${verb}” za ‘${nodeName}’`,
    descendantsSection: 'Podređeni čvorovi (ako se razlikuju)',
    dialogInstructions: 'Postavite dozvolu za ovaj čvor. Prema zadanim postavkama, ovo vrijedi i za sve podređene čvorove. Upotrijebite „Podređeni čvorovi (ako se razlikuju)” kako biste postavili drukčiju dozvolu za podređene čvorove.',
    virtualRootInherit: 'Nije postavljeno (ukloni unos)',
    virtualRootAllow: 'Dozvoli (sav sadržaj)',
    virtualRootDeny: 'Zabrani (sav sadržaj)',
    dialogResult: 'Rezultat',
    previewBothInherit: 'Dozvola nije postavljena. Nasljeđuje se od nadređenog čvora.',
    previewUniform: (action: string) => `${action} za ovaj čvor i sve podređene čvorove.`,
    previewNodeOnly: (action: string) => `${action} samo za ovaj čvor. Podređeni čvorovi nisu obuhvaćeni ovim pravilom.`,
    previewDescOnly: (action: string) => `Nema izričite dozvole za ovaj čvor. ${action} za sve podređene čvorove.`,
    previewSplit: (nodeAction: string, descAction: string) => `${nodeAction} za ovaj čvor. ${descAction} za sve podređene čvorove.`,
    previewVirtualInherit: 'Zadana dozvola nije postavljena.',
    previewVirtualSet: (action: string) => `${action} prema zadanim postavkama za sav sadržaj.`,
    previewPriorityNode: 'Prioritetno nadjačavanje postavljeno je za ovaj čvor.',
    previewPriorityDesc: 'Prioritetno nadjačavanje postavljeno je za podređene čvorove.',
    previewPriorityBoth: 'Prioritetno nadjačavanje je postavljeno.',

    // ── Prioritetno nadjačavanje ──────────────────────────────────────
    priorityOverride: 'Prioritetno nadjačavanje',
    priorityOverrideTooltip: (permission: string, nodeName: string) =>
      `Korisnik može pripadati nekolicini grupa korisnika. Uobičajeno, efektivna dozvola slijedi utvrđeni redoslijed prioriteta. Označavanjem ovog okvira taj se redoslijed nadjačava, tako da ovdje odabrana postavka „${permission}” gotovo uvijek postaje rezultat za „${nodeName}”, neovisno o ostalim grupama korisnika. Koristite umjereno.`,
    priorityOverrideBadgeTitle: 'Prioritetno nadjačavanje postavljeno je za ovaj unos',
    priorityOverrideWonTitle: 'Razriješeno putem prioritetnog nadjačavanja',
    priorityOverrideSuppressedHeader: 'Prioritetno nadjačavanje promijenilo je rezultat',
    priorityOverrideSuppressedHint: 'Bez njega bi rezultat bio:',

    // ── Prikaz pristupa ───────────────────────────────────────────────────
    viewerHeadline: 'Prikaz pristupa',
    byRole: 'Po grupi korisnika',
    byUser: 'Po korisniku',
    chooseRole: 'Odaberi grupu korisnika',
    chooseUser: 'Odaberi korisnika',
    selectSubjectPrompt: 'Odaberite grupu korisnika ili korisnika za pregled efektivnih dozvola.',
    legendAllow: 'Dozvoli',
    legendDeny: 'Zabrani',
    clickForReasoning: (label: string) => `${label} — kliknite za obrazloženje`,
    subjectOr: 'ili',

    // ── Dijalog za odabir grupe korisnika ──────────────────────────────────
    rolePickerHeadline: 'Odaberite grupu korisnika',
    rolePickerFilter: 'Upišite za filtriranje…',
    rolePickerNoResults: 'Nijedna grupa korisnika ne odgovara filtru.',
    rolePickerNameHeader: 'Grupa korisnika',

    // ── Dijalog za odabir korisnika ─────────────────────────────────────────
    userPickerHeadline: 'Odaberite korisnika',
    userPickerFilter: 'Upišite za filtriranje…',
    userPickerNoResults: 'Nijedan korisnik ne odgovara filtru.',
    userPickerNameHeader: 'Korisnik',

    // ── Dijalog obrazloženja ──────────────────────────────────────────────
    reasoningHeadline: (verb: string, nodeName: string) => `Dozvola „${verb}” za “${nodeName}”`,
    effectiveAllowed: (subject: string, verb: string, nodeName: string) =>
      `${subject} ima dozvoljenu dozvolu „${verb}” za “${nodeName}”.`,
    effectiveDenied: (subject: string, verb: string, nodeName: string) =>
      `${subject} ima zabranjenu dozvolu „${verb}” za “${nodeName}”.`,
    dialogSecurityHeader: 'Sigurnost',
    defaultPermissions: 'Zadane dozvole',
    determiningEntry: 'Ovaj unos ima prednost',
    noReasoningData: 'Nema dostupnih podataka o dozvolama za ovu radnju.',
    defaultAllowNote: 'Nisu postavljene dozvole, ovo je dozvoljeno prema zadanim postavkama.',
    defaultDenyNote: 'Nisu postavljene dozvole, ovo je zabranjeno prema zadanim postavkama.',

    // ── Poruka preusmjeravanja granuliranih dozvola ───────────────────────
    redirectMessage:
      'Dozvolama dokumenata za ovu grupu korisnika upravlja paket Advanced Permissions. Otvorite Uređivač dozvola u sekciji Korisnici kako biste konfigurirali dozvole.',

    // ── Dozvole vrste dokumenta ───────────────────────────────────────────
    role: 'Grupa korisnika',
    pickRole: 'Odaberi grupu korisnika',
    user: 'Korisnik',
    pickUser: 'Odaberi korisnika',
    node: 'Čvor',
    pickNode: 'Odaberi čvor',
    state: 'Status',
    scope: 'Opseg',
    scope_thisNodeOnly: 'Samo ovaj čvor',
    scope_thisNodeAndDescendants: 'Ovaj čvor i podređeni čvorovi',
    scope_descendantsOnly: 'Samo podređeni čvorovi',

    docTypePermissions_menuLabel: 'Uređivač dozvola vrste dokumenta',
    docTypePermissions_insertOptionsMenuLabel: 'Prikaz opcija umetanja',
    docTypePermissions_workspaceTitle: 'Uređivač dozvola vrste dokumenta',
    docTypePermissions_auditTitle: 'Prikaz opcija umetanja',
    docTypePermissions_allDocTypes: 'Sve vrste dokumenata',
    docTypePermissions_verbInsert: 'Umetni',
    docTypePermissions_documentType: 'Vrsta dokumenta',
    chooseDocType: 'Odaberi vrstu dokumenta',
    notAnInsertOption: 'Ova vrsta dokumenta trenutno nije opcija umetanja za ovaj čvor.',
    notAnInsertOptionAllowedNote: 'Ova vrsta dokumenta nije opcija umetanja za ovaj čvor, ali bi inače bila dozvoljena.',
    notAnInsertOptionDeniedNote: 'Ova vrsta dokumenta nije opcija umetanja za ovaj čvor, ali bi inače bila zabranjena.',
    docTypePermissions_pickDocType: '— Odaberite vrstu dokumenta —',
    docTypePermissions_pickToStart: 'Odaberite grupu korisnika i vrstu dokumenta za početak.',
    docTypePermissions_defaultRowLabel: 'Zadano (vrijedi svuda)',
    docTypePermissions_pendingNodeLabel: '(nespremljeni čvor)',
    docTypePermissions_addScopeNode: 'Dodaj nadjačavanje opsega',
    docTypePermissions_notSet: 'Nije postavljeno',
    docTypePermissions_noResults: 'Nije pronađena nijedna vrsta dokumenta.',
    docTypePermissions_useRoot: 'Koristi korijen',
    docTypePermissions_pickedNode: 'Čvor:',
    docTypePermissions_rootLevel: 'Korijenska razina',
    docTypePermissions_reasoning: 'Obrazloženje',
    docTypePermissions_defaultAllow: 'Dozvoljeno prema zadanim postavkama',
    docTypePermissions_viaDefault: 'iz zadanog retka',
    // -- i18n completion (machine-translated, pending review) --
    help_contentPermissions_description: 'Upravljajte dozvolama Dozvoli/Zabrani po grupi korisnika kroz stablo sadržaja.',
    help_accessViewer_description: 'Pogledajte efektivne dozvole koje korisnik ili grupa ima na bilo kojem čvoru, s potpunim obrazloženjem.',
    help_docTypePermissions_description: 'Odlučite koje vrste dokumenata svaka grupa korisnika može stvarati i gdje.',
    help_insertOptions_description: 'Provjerite koje vrste dokumenata korisnik ili grupa korisnika može stvarati na svakom čvoru.',
    help_libraryPermissions_description: 'Upravljajte dozvolama Dozvoli/Zabrani po grupi korisnika kroz stablo Library.',
    help_elementTypePermissions_description: 'Kontrolirajte koje vrste elemenata svaka grupa korisnika može koristiti u Library.',
    help_libraryAccessViewer_description: 'Pogledajte efektivne dozvole za Library koje korisnik ili grupa korisnika ima na svakom čvoru.',
    help_libraryInsertViewer_description: 'Provjerite koje vrste elemenata korisnik ili grupa korisnika može umetati u Library.',
    help_learnMore: 'Saznajte više',
    help_modalTitle: 'Pomoć',
    help_tabAbout: 'O ovoj stranici',
    help_tabConcepts: 'Pojmovi',
    help_concept_scope_tip: 'Opseg određuje koliko daleko pravilo doseže: ovaj čvor, ovaj čvor i njegovi podređeni čvorovi ili samo podređeni čvorovi.',
    help_concept_priorityOverride_tip: 'Prioritetno nadjačavanje prisiljava ovaj unos da pobijedi nad uobičajenim redoslijedom razrješavanja.',
    help_concept_allowDeny_tip: 'Dozvoli daje dozvolu, Zabrani je oduzima, a ostavljanje nepostavljenim nasljeđuje se od najbližeg nadređenog čvora.',
    help_concept_reasoning_tip: 'Kliknite bilo koju ćeliju da vidite točno kako je dozvola razriješena.',
    previewElementFolderSet: (action: string) => `Ne odnosi se na ovu mapu. ${action} za elemente unutar nje.`,
    previewElementFolderInherit: 'Ne odnosi se na ovu mapu. Elementi unutar nje nasljeđuju od svojeg nadređenog čvora.',
    dialogElementFolderNote: (verb: string) => `„${verb}” se ne odnosi na mapu — samo na elemente unutar nje.`,
    elementFolderDescSection: 'Elementi unutra',
    naChip: 'N/P',
    redirectMessageElement:
      'Dozvolama za Library (elemente) za ovu grupu korisnika upravlja paket Advanced Permissions. Otvorite Uređivač dozvola za Library u sekciji Korisnici kako biste konfigurirali dozvole.',
    library_menuLabel: 'Uređivač dozvola za Library',
    library_editorHeadline: 'Uređivač dozvola za Library',
    library_accessViewerMenuLabel: 'Prikaz pristupa za Library',
    library_accessViewerHeadline: 'Prikaz pristupa za Library',
    library_nodeHeader: 'Stavka Library',
    library_root: 'Zadane dozvole',
    library_selectRolePrompt: 'Odaberite grupu korisnika kako biste upravljali njezinim dozvolama za Library.',
    library_permissionsSaved: 'Dozvole za Library su spremljene.',
    library_notApplicableTitle: (verb: string) => `${verb} se ne odnosi na mape — i dalje se može postaviti za stavke unutar njih.`,
    library_folderInheritLabel: 'Stavke unutra (podređeni čvorovi)',
    libraryInsertViewer_menuLabel: 'Prikaz umetanja za Library',
    libraryInsertViewer_headline: 'Prikaz umetanja za Library',
    libraryInsertViewer_intro: 'Prikazuje koje vrste elemenata Library grupa korisnika ili korisnik može stvarati, razriješeno kroz sve njihove grupe. Kliknite redak da vidite obrazloženje.',
    elementTypePermissions_menuLabel: 'Dozvole vrsta elemenata za Library',
    elementTypePermissions_headline: 'Dozvole vrsta elemenata za Library',
    elementTypePermissions_intro: 'Kontrolirajte koje vrste elemenata svaka grupa korisnika može stvarati u Library. Vrste elemenata su prema zadanim postavkama dostupne za stvaranje; postavite Dozvoli ili Zabrani — uz neobavezno prioritetno nadjačavanje — kako biste kontrolirali način razrješavanja izbora kada korisnik pripada nekolicini grupa.',
    elementTypePermissions_typeHeader: 'Vrsta elementa',
    elementTypePermissions_verbCreate: 'Stvori u Library',
    elementTypePermissions_noTypes: 'Nije pronađena nijedna vrsta elementa za Library. Označite vrstu dokumenta kao vrstu elementa i omogućite „Dozvoli u Library”.',
    elementType_dialogHeadline: (type: string) => `Dozvola stvaranja za ‘${type}’ u Library`,
    elementType_inheritLabel: 'Nije postavljeno (dozvoljeno prema zadanim postavkama)',
    elementType_allowLabel: 'Dozvoli (može se stvarati u Library)',
    elementType_denyLabel: 'Zabrani (skriveno iz Library)',
    elementType_previewInherit: 'Nema izričitog pravila. Ova vrsta elementa može se stvarati u Library prema zadanim postavkama.',
    elementType_previewSet: (action: string) => `${action} stvaranje ove vrste elementa u Library.`,
  },
} satisfies UmbLocalizationDictionary;
