import type { UmbLocalizationDictionary } from '@umbraco-cms/backoffice/localization-api';

export default {
  uap: {
    // ── Navigazione ───────────────────────────────────────────────────────
    sectionLabel: 'Permessi avanzati',
    editorsSectionLabel: 'Editor',
    viewersSectionLabel: 'Visualizzazioni',
    permissionsEditor: 'Editor dei permessi sui contenuti',
    accessViewer: 'Visualizzatore degli accessi',

    // ── Generale ──────────────────────────────────────────────────────────
    roleLabel: 'Gruppo di utenti',
    rolePlaceholder: '— Seleziona un gruppo di utenti —',
    userLabel: 'Utente',
    saveChanges: 'Salva modifiche',
    discard: 'Scarta',
    cancel: 'Annulla',
    apply: 'Applica',
    close: 'Chiudi',
    inherit: 'Eredita',
    allow: 'Consenti',
    deny: 'Nega',
    umbracoUsers: 'Tutti gli utenti',

    // ── Editor dei permessi ───────────────────────────────────────────────
    editorHeadline: 'Editor dei permessi sui contenuti',
    selectRolePrompt: 'Seleziona un gruppo di utenti qui sopra per gestirne i permessi.',
    permissionsSaved: 'Permessi salvati.',
    saveFailed: (error: string) => `Salvataggio non riuscito: ${error}`,
    contentNodeHeader: 'Nodo di contenuto',
    contentRoot: 'Permessi predefiniti',
    expand: 'Espandi',
    collapse: 'Comprimi',

    // ── Finestra dei permessi ─────────────────────────────────────────────
    dialogHeadline: (verb: string, nodeName: string) => `Imposta il permesso ${verb} per ‘${nodeName}’`,
    descendantsSection: 'Discendenti (se diversi)',
    dialogInstructions: 'Imposta il permesso per questo nodo. Per impostazione predefinita, questo si applica anche a tutti i discendenti. Usa “Discendenti (se diversi)” per impostare un permesso diverso per i nodi discendenti.',
    virtualRootInherit: 'Non impostato (rimuovi voce)',
    virtualRootAllow: 'Consenti (tutti i contenuti)',
    virtualRootDeny: 'Nega (tutti i contenuti)',
    dialogResult: 'Risultato',
    previewBothInherit: 'Nessun permesso impostato. Eredita dal nodo padre.',
    previewUniform: (action: string) => `${action} su questo nodo e su tutti i discendenti.`,
    previewNodeOnly: (action: string) => `${action} solo su questo nodo. I discendenti non sono interessati da questa regola.`,
    previewDescOnly: (action: string) => `Nessun permesso esplicito su questo nodo. ${action} su tutti i discendenti.`,
    previewSplit: (nodeAction: string, descAction: string) => `${nodeAction} su questo nodo. ${descAction} su tutti i discendenti.`,
    previewVirtualInherit: 'Nessun permesso predefinito impostato.',
    previewVirtualSet: (action: string) => `${action} per impostazione predefinita per tutti i contenuti.`,
    previewPriorityNode: 'La sostituzione prioritaria è impostata su questo nodo.',
    previewPriorityDesc: 'La sostituzione prioritaria è impostata sui discendenti.',
    previewPriorityBoth: 'La sostituzione prioritaria è impostata.',

    // ── Sostituzione prioritaria ──────────────────────────────────────────
    priorityOverride: 'Sostituzione prioritaria',
    priorityOverrideTooltip: (permission: string, nodeName: string) =>
      `Un utente può appartenere a più gruppi di utenti. Normalmente, il permesso effettivo segue un ordine di priorità fisso. Selezionando questa casella si sostituisce tale ordine, così l’impostazione “${permission}” scelta qui diventa quasi sempre il risultato per “${nodeName}”, indipendentemente dagli altri gruppi dell’utente. Usare con parsimonia.`,
    priorityOverrideBadgeTitle: 'La sostituzione prioritaria è impostata su questa voce',
    priorityOverrideWonTitle: 'Risolto tramite sostituzione prioritaria',
    priorityOverrideSuppressedHeader: 'La sostituzione prioritaria ha cambiato il risultato',
    priorityOverrideSuppressedHint: 'Senza di essa, il risultato sarebbe stato:',

    // ── Visualizzatore degli accessi ──────────────────────────────────────
    viewerHeadline: 'Visualizzatore degli accessi',
    byRole: 'Per gruppo di utenti',
    byUser: 'Per utente',
    chooseRole: 'Scegli gruppo di utenti',
    chooseUser: 'Scegli utente',
    selectSubjectPrompt: 'Seleziona un gruppo di utenti o un utente per visualizzare i permessi effettivi.',
    legendAllow: 'Consenti',
    legendDeny: 'Nega',
    clickForReasoning: (label: string) => `${label} — clicca per la motivazione`,
    subjectOr: 'o',

    // ── Finestra di selezione gruppo di utenti ────────────────────────────
    rolePickerHeadline: 'Seleziona un gruppo di utenti',
    rolePickerFilter: 'Digita per filtrare…',
    rolePickerNoResults: 'Nessun gruppo di utenti corrisponde al filtro.',
    rolePickerNameHeader: 'Gruppo di utenti',

    // ── Finestra di selezione utente ──────────────────────────────────────
    userPickerHeadline: 'Seleziona un utente',
    userPickerFilter: 'Digita per filtrare…',
    userPickerNoResults: 'Nessun utente corrisponde al filtro.',
    userPickerNameHeader: 'Utente',

    // ── Finestra della motivazione ────────────────────────────────────────
    reasoningHeadline: (verb: string, nodeName: string) => `Permesso ${verb} per “${nodeName}”`,
    effectiveAllowed: (subject: string, verb: string, nodeName: string) =>
      `A ${subject} è stato consentito il permesso ${verb} per “${nodeName}”.`,
    effectiveDenied: (subject: string, verb: string, nodeName: string) =>
      `A ${subject} è stato negato il permesso ${verb} per “${nodeName}”.`,
    dialogSecurityHeader: 'Sicurezza',
    defaultPermissions: 'Permessi predefiniti',
    determiningEntry: 'Questa voce ha la precedenza',
    noReasoningData: 'Nessun dato sui permessi disponibile per questo verbo.',
    defaultAllowNote: 'Nessun permesso impostato, questo è consentito per impostazione predefinita.',
    defaultDenyNote: 'Nessun permesso impostato, questo è negato per impostazione predefinita.',

    // ── Messaggio di reindirizzamento permessi granulari ──────────────────
    redirectMessage:
      'I permessi sui documenti per questo gruppo di utenti sono gestiti dal pacchetto Advanced Permissions. Apri l’Editor dei permessi nella sezione Utenti per configurare i permessi.',

    // ── Permessi per tipo di documento ────────────────────────────────────
    role: 'Gruppo di utenti',
    pickRole: 'Scegli gruppo di utenti',
    user: 'Utente',
    pickUser: 'Scegli utente',
    node: 'Nodo',
    pickNode: 'Scegli nodo',
    state: 'Stato',
    scope: 'Ambito',
    scope_thisNodeOnly: 'Solo questo nodo',
    scope_thisNodeAndDescendants: 'Questo nodo e i discendenti',
    scope_descendantsOnly: 'Solo i discendenti',

    docTypePermissions_menuLabel: 'Editor dei permessi per tipo di documento',
    docTypePermissions_insertOptionsMenuLabel: 'Visualizzatore delle opzioni di inserimento',
    docTypePermissions_workspaceTitle: 'Editor dei permessi per tipo di documento',
    docTypePermissions_auditTitle: 'Visualizzatore delle opzioni di inserimento',
    docTypePermissions_allDocTypes: 'Tutti i tipi di documento',
    docTypePermissions_verbInsert: 'Inserisci',
    docTypePermissions_documentType: 'Tipo di documento',
    chooseDocType: 'Scegli tipo di documento',
    notAnInsertOption: 'Questo tipo di documento attualmente non è un’opzione di inserimento su questo nodo.',
    notAnInsertOptionAllowedNote: 'Questo tipo di documento non è un’opzione di inserimento su questo nodo, ma altrimenti sarebbe consentito.',
    notAnInsertOptionDeniedNote: 'Questo tipo di documento non è un’opzione di inserimento su questo nodo, ma altrimenti sarebbe negato.',
    docTypePermissions_pickDocType: '— Seleziona un tipo di documento —',
    docTypePermissions_pickToStart: 'Scegli un gruppo di utenti e un tipo di documento per iniziare.',
    docTypePermissions_defaultRowLabel: 'Predefinito (si applica ovunque)',
    docTypePermissions_pendingNodeLabel: '(nodo non salvato)',
    docTypePermissions_addScopeNode: 'Aggiungi sostituzione dell’ambito',
    docTypePermissions_notSet: 'Non impostato',
    docTypePermissions_noResults: 'Nessun tipo di documento trovato.',
    docTypePermissions_useRoot: 'Usa root',
    docTypePermissions_pickedNode: 'Nodo:',
    docTypePermissions_rootLevel: 'Livello root',
    docTypePermissions_reasoning: 'Motivazione',
    docTypePermissions_defaultAllow: 'Consentito per impostazione predefinita',
    docTypePermissions_viaDefault: 'dalla riga predefinita',
    // -- i18n completion (machine-translated, pending review) --
    help_contentPermissions_description: 'Gestisci i permessi Consenti/Nega per ogni gruppo di utenti nell’albero dei contenuti.',
    help_accessViewer_description: 'Visualizza i permessi effettivi di un utente o gruppo su qualsiasi nodo, con la motivazione completa.',
    help_docTypePermissions_description: 'Decidi quali tipi di documento ogni gruppo di utenti può creare e dove.',
    help_insertOptions_description: 'Verifica quali tipi di documento un utente o un gruppo di utenti può creare su ciascun nodo.',
    help_libraryPermissions_description: 'Gestisci i permessi Consenti/Nega per ogni gruppo di utenti nell’albero della Library.',
    help_elementTypePermissions_description: 'Controlla quali tipi di elemento ogni gruppo di utenti può usare nella Library.',
    help_libraryAccessViewer_description: 'Visualizza i permessi effettivi della Library di un utente o gruppo di utenti su ciascun nodo.',
    help_libraryInsertViewer_description: 'Verifica quali tipi di elemento un utente o un gruppo di utenti può inserire nella Library.',
    help_learnMore: 'Scopri di più',
    help_modalTitle: 'Guida',
    help_tabAbout: 'Informazioni su questa pagina',
    help_tabConcepts: 'Concetti',
    help_concept_scope_tip: 'L’ambito determina fin dove arriva una regola: questo nodo, questo nodo e i suoi discendenti, oppure solo i discendenti.',
    help_concept_priorityOverride_tip: 'La sostituzione prioritaria forza questa voce a prevalere sul normale ordine di risoluzione.',
    help_concept_allowDeny_tip: 'Consenti concede il permesso, Nega lo revoca e, lasciandolo non impostato, viene ereditato dall’antenato più vicino.',
    help_concept_reasoning_tip: 'Clicca su qualsiasi cella per vedere esattamente come è stato risolto il permesso.',
    previewElementFolderSet: (action: string) => `Non si applica a questa cartella. ${action} sugli elementi al suo interno.`,
    previewElementFolderInherit: 'Non si applica a questa cartella. Gli elementi al suo interno ereditano dal nodo padre.',
    dialogElementFolderNote: (verb: string) => `“${verb}” non si applica a una cartella, ma solo agli elementi al suo interno.`,
    elementFolderDescSection: 'Elementi all’interno',
    naChip: 'N/D',
    redirectMessageElement:
      'I permessi della Library (elementi) per questo gruppo di utenti sono gestiti dal pacchetto Advanced Permissions. Apri l’Editor dei permessi della Library nella sezione Utenti per configurare i permessi.',
    library_menuLabel: 'Editor dei permessi della Library',
    library_editorHeadline: 'Editor dei permessi della Library',
    library_accessViewerMenuLabel: 'Visualizzatore degli accessi della Library',
    library_accessViewerHeadline: 'Visualizzatore degli accessi della Library',
    library_nodeHeader: 'Elemento della Library',
    library_root: 'Permessi predefiniti',
    library_selectRolePrompt: 'Seleziona un gruppo di utenti per gestirne i permessi della Library.',
    library_permissionsSaved: 'Permessi della Library salvati.',
    library_notApplicableTitle: (verb: string) => `${verb} non si applica alle cartelle, ma può comunque essere impostato per gli elementi al loro interno.`,
    library_folderInheritLabel: 'Elementi all’interno (discendenti)',
    libraryInsertViewer_menuLabel: 'Visualizzatore degli inserimenti della Library',
    libraryInsertViewer_headline: 'Visualizzatore degli inserimenti della Library',
    libraryInsertViewer_intro: 'Mostra quali tipi di elemento della Library un gruppo di utenti o un utente può creare, risolti su tutti i suoi gruppi. Clicca su una riga per vedere la motivazione.',
    elementTypePermissions_menuLabel: 'Permessi per tipo di elemento della Library',
    elementTypePermissions_headline: 'Permessi per tipo di elemento della Library',
    elementTypePermissions_intro: 'Controlla quali tipi di elemento ogni gruppo di utenti può creare nella Library. I tipi di elemento sono creabili per impostazione predefinita; imposta Consenti o Nega — con un’eventuale sostituzione prioritaria — per controllare come viene risolta la scelta quando un utente appartiene a più gruppi.',
    elementTypePermissions_typeHeader: 'Tipo di elemento',
    elementTypePermissions_verbCreate: 'Crea nella Library',
    elementTypePermissions_noTypes: 'Nessun tipo di elemento della Library trovato. Contrassegna un tipo di documento come tipo di elemento e abilita “Consenti nella Library”.',
    elementType_dialogHeadline: (type: string) => `Permesso di creazione per ‘${type}’ nella Library`,
    elementType_inheritLabel: 'Non impostato (consentito per impostazione predefinita)',
    elementType_allowLabel: 'Consenti (creabile nella Library)',
    elementType_denyLabel: 'Nega (nascosto dalla Library)',
    elementType_previewInherit: 'Nessuna regola esplicita. Questo tipo di elemento è creabile nella Library per impostazione predefinita.',
    elementType_previewSet: (action: string) => `${action} la creazione di questo tipo di elemento nella Library.`,
  },
} satisfies UmbLocalizationDictionary;
