import type { UmbLocalizationDictionary } from '@umbraco-cms/backoffice/localization-api';

export default {
  uap: {
    // ── Nawigacja ─────────────────────────────────────────────────────────
    sectionLabel: 'Zaawansowane uprawnienia',
    editorsSectionLabel: 'Edytorzy',
    viewersSectionLabel: 'Podglądy',
    permissionsEditor: 'Edytor uprawnień do treści',
    accessViewer: 'Podgląd dostępu',

    // ── Wspólne ───────────────────────────────────────────────────────────
    roleLabel: 'Grupa użytkowników',
    rolePlaceholder: '— Wybierz grupę użytkowników —',
    userLabel: 'Użytkownik',
    saveChanges: 'Zapisz zmiany',
    discard: 'Odrzuć',
    cancel: 'Anuluj',
    apply: 'Zastosuj',
    close: 'Zamknij',
    inherit: 'Dziedzicz',
    allow: 'Zezwól',
    deny: 'Odmów',
    umbracoUsers: 'Wszyscy użytkownicy',

    // ── Edytor uprawnień ─────────────────────────────────────────────────
    editorHeadline: 'Edytor uprawnień do treści',
    selectRolePrompt: 'Wybierz powyżej grupę użytkowników, aby zarządzać jej uprawnieniami.',
    permissionsSaved: 'Uprawnienia zapisane.',
    saveFailed: (error: string) => `Zapisywanie nie powiodło się: ${error}`,
    contentNodeHeader: 'Węzeł treści',
    contentRoot: 'Uprawnienia domyślne',
    expand: 'Rozwiń',
    collapse: 'Zwiń',

    // ── Okno dialogowe uprawnień ──────────────────────────────────────────
    dialogHeadline: (verb: string, nodeName: string) => `Ustaw uprawnienie „${verb}” dla ‘${nodeName}’`,
    descendantsSection: 'Elementy podrzędne (jeśli inne)',
    dialogInstructions: 'Ustaw uprawnienie dla tego węzła. Domyślnie dotyczy ono również wszystkich elementów podrzędnych. Użyj opcji „Elementy podrzędne (jeśli inne)”, aby ustawić inne uprawnienie dla węzłów podrzędnych.',
    virtualRootInherit: 'Nie ustawiono (usuń wpis)',
    virtualRootAllow: 'Zezwól (cała treść)',
    virtualRootDeny: 'Odmów (cała treść)',
    dialogResult: 'Wynik',
    previewBothInherit: 'Nie ustawiono uprawnienia. Dziedziczy z elementu nadrzędnego.',
    previewUniform: (action: string) => `${action} dla tego węzła i wszystkich elementów podrzędnych.`,
    previewNodeOnly: (action: string) => `${action} tylko dla tego węzła. Elementy podrzędne nie są objęte tą regułą.`,
    previewDescOnly: (action: string) => `Brak jawnego uprawnienia dla tego węzła. ${action} dla wszystkich elementów podrzędnych.`,
    previewSplit: (nodeAction: string, descAction: string) => `${nodeAction} dla tego węzła. ${descAction} dla wszystkich elementów podrzędnych.`,
    previewVirtualInherit: 'Nie ustawiono uprawnienia domyślnego.',
    previewVirtualSet: (action: string) => `${action} domyślnie dla całej treści.`,
    previewPriorityNode: 'Nadpisanie priorytetu jest ustawione dla tego węzła.',
    previewPriorityDesc: 'Nadpisanie priorytetu jest ustawione dla elementów podrzędnych.',
    previewPriorityBoth: 'Nadpisanie priorytetu jest ustawione.',

    // ── Nadpisanie priorytetu ─────────────────────────────────────────
    priorityOverride: 'Nadpisanie priorytetu',
    priorityOverrideTooltip: (permission: string, nodeName: string) =>
      `Użytkownik może należeć do kilku grup użytkowników. Zwykle efektywne uprawnienie wynika ze stałej kolejności priorytetów. Zaznaczenie tego pola nadpisuje tę kolejność, dzięki czemu wybrane tutaj ustawienie „${permission}” niemal zawsze staje się wynikiem dla „${nodeName}”, niezależnie od pozostałych grup użytkownika. Używaj oszczędnie.`,
    priorityOverrideBadgeTitle: 'Nadpisanie priorytetu jest ustawione dla tego wpisu',
    priorityOverrideWonTitle: 'Rozstrzygnięto przez nadpisanie priorytetu',
    priorityOverrideSuppressedHeader: 'Nadpisanie priorytetu zmieniło wynik',
    priorityOverrideSuppressedHint: 'Bez niego wynik byłby następujący:',

    // ── Podgląd dostępu ──────────────────────────────────────────────────
    viewerHeadline: 'Podgląd dostępu',
    byRole: 'Według grupy użytkowników',
    byUser: 'Według użytkownika',
    chooseRole: 'Wybierz grupę użytkowników',
    chooseUser: 'Wybierz użytkownika',
    selectSubjectPrompt: 'Wybierz grupę użytkowników lub użytkownika, aby zobaczyć efektywne uprawnienia.',
    legendAllow: 'Zezwól',
    legendDeny: 'Odmów',
    clickForReasoning: (label: string) => `${label} — kliknij, aby zobaczyć uzasadnienie`,
    subjectOr: 'lub',

    // ── Okno wyboru grupy użytkowników ──────────────────────────────────
    rolePickerHeadline: 'Wybierz grupę użytkowników',
    rolePickerFilter: 'Wpisz, aby filtrować…',
    rolePickerNoResults: 'Brak grup użytkowników pasujących do filtra.',
    rolePickerNameHeader: 'Grupa użytkowników',

    // ── Okno wyboru użytkownika ──────────────────────────────────────────
    userPickerHeadline: 'Wybierz użytkownika',
    userPickerFilter: 'Wpisz, aby filtrować…',
    userPickerNoResults: 'Brak użytkowników pasujących do filtra.',
    userPickerNameHeader: 'Użytkownik',

    // ── Okno uzasadnienia ─────────────────────────────────────────────────
    reasoningHeadline: (verb: string, nodeName: string) => `Uprawnienie „${verb}” dla „${nodeName}”`,
    effectiveAllowed: (subject: string, verb: string, nodeName: string) =>
      `${subject} otrzymał(a) uprawnienie „${verb}” dla „${nodeName}”.`,
    effectiveDenied: (subject: string, verb: string, nodeName: string) =>
      `${subject} odmówiono uprawnienia „${verb}” dla „${nodeName}”.`,
    dialogSecurityHeader: 'Bezpieczeństwo',
    defaultPermissions: 'Uprawnienia domyślne',
    determiningEntry: 'Ten wpis ma pierwszeństwo',
    noReasoningData: 'Brak danych o uprawnieniach dla tego uprawnienia.',
    defaultAllowNote: 'Nie ustawiono żadnych uprawnień, jest to domyślnie dozwolone.',
    defaultDenyNote: 'Nie ustawiono żadnych uprawnień, jest to domyślnie odmawiane.',

    // ── Komunikat przekierowania uprawnień szczegółowych ─────────────────
    redirectMessage:
      'Uprawnienia do dokumentów dla tej grupy użytkowników są zarządzane przez pakiet Advanced Permissions. Otwórz Edytor uprawnień w sekcji Użytkownicy, aby skonfigurować uprawnienia.',

    // ── Uprawnienia typów dokumentów ──────────────────────────────────────
    role: 'Grupa użytkowników',
    pickRole: 'Wybierz grupę użytkowników',
    user: 'Użytkownik',
    pickUser: 'Wybierz użytkownika',
    node: 'Węzeł',
    pickNode: 'Wybierz węzeł',
    state: 'Status',
    scope: 'Zakres',
    scope_thisNodeOnly: 'Tylko ten węzeł',
    scope_thisNodeAndDescendants: 'Ten węzeł i elementy podrzędne',
    scope_descendantsOnly: 'Tylko elementy podrzędne',

    docTypePermissions_menuLabel: 'Edytor uprawnień typów dokumentów',
    docTypePermissions_insertOptionsMenuLabel: 'Podgląd opcji wstawiania',
    docTypePermissions_workspaceTitle: 'Edytor uprawnień typów dokumentów',
    docTypePermissions_auditTitle: 'Podgląd opcji wstawiania',
    docTypePermissions_allDocTypes: 'Wszystkie typy dokumentów',
    docTypePermissions_verbInsert: 'Wstaw',
    docTypePermissions_documentType: 'Typ dokumentu',
    chooseDocType: 'Wybierz typ dokumentu',
    notAnInsertOption: 'Ten typ dokumentu nie jest obecnie opcją wstawiania dla tego węzła.',
    notAnInsertOptionAllowedNote: 'Ten typ dokumentu nie jest opcją wstawiania dla tego węzła, ale w innym przypadku byłby dozwolony.',
    notAnInsertOptionDeniedNote: 'Ten typ dokumentu nie jest opcją wstawiania dla tego węzła, ale w innym przypadku byłby odmawiany.',
    docTypePermissions_pickDocType: '— Wybierz typ dokumentu —',
    docTypePermissions_pickToStart: 'Wybierz grupę użytkowników i typ dokumentu, aby rozpocząć.',
    docTypePermissions_defaultRowLabel: 'Domyślne (dotyczy wszędzie)',
    docTypePermissions_pendingNodeLabel: '(niezapisany węzeł)',
    docTypePermissions_addScopeNode: 'Dodaj nadpisanie zakresu',
    docTypePermissions_notSet: 'Nie ustawiono',
    docTypePermissions_noResults: 'Nie znaleziono typów dokumentów.',
    docTypePermissions_useRoot: 'Użyj korzenia',
    docTypePermissions_pickedNode: 'Węzeł:',
    docTypePermissions_rootLevel: 'Poziom korzenia',
    docTypePermissions_reasoning: 'Uzasadnienie',
    docTypePermissions_defaultAllow: 'Domyślnie dozwolone',
    docTypePermissions_viaDefault: 'z wiersza domyślnego',
    // -- i18n completion (machine-translated, pending review) --
    help_contentPermissions_description: 'Zarządzaj uprawnieniami Zezwól/Odmów dla każdej grupy użytkowników w całym drzewie treści.',
    help_accessViewer_description: 'Zobacz efektywne uprawnienia, jakie użytkownik lub grupa ma w dowolnym węźle, wraz z pełnym uzasadnieniem.',
    help_docTypePermissions_description: 'Zdecyduj, które typy dokumentów może tworzyć każda grupa użytkowników i gdzie.',
    help_insertOptions_description: 'Sprawdź, które typy dokumentów użytkownik lub grupa użytkowników może tworzyć w każdym węźle.',
    help_libraryPermissions_description: 'Zarządzaj uprawnieniami Zezwól/Odmów dla każdej grupy użytkowników w całym drzewie Library.',
    help_elementTypePermissions_description: 'Określ, których typów elementów może używać każda grupa użytkowników w Library.',
    help_libraryAccessViewer_description: 'Zobacz efektywne uprawnienia Library, jakie użytkownik lub grupa użytkowników ma w każdym węźle.',
    help_libraryInsertViewer_description: 'Sprawdź, które typy elementów użytkownik lub grupa użytkowników może wstawiać w Library.',
    help_learnMore: 'Dowiedz się więcej',
    help_modalTitle: 'Pomoc',
    help_tabAbout: 'O tej stronie',
    help_tabConcepts: 'Pojęcia',
    help_concept_scope_tip: 'Zakres określa, jak daleko sięga reguła: ten węzeł, ten węzeł i jego elementy podrzędne lub tylko elementy podrzędne.',
    help_concept_priorityOverride_tip: 'Nadpisanie priorytetu wymusza, aby ten wpis miał pierwszeństwo nad zwykłą kolejnością rozstrzygania.',
    help_concept_allowDeny_tip: 'Zezwól przyznaje uprawnienie, Odmów je odbiera, a pozostawienie go nieustawionego powoduje dziedziczenie od najbliższego elementu nadrzędnego.',
    help_concept_reasoning_tip: 'Kliknij dowolną komórkę, aby zobaczyć dokładnie, jak zostało rozstrzygnięte uprawnienie.',
    previewElementFolderSet: (action: string) => `Nie dotyczy tego folderu. ${action} dla elementów znajdujących się w nim.`,
    previewElementFolderInherit: 'Nie dotyczy tego folderu. Elementy znajdujące się w nim dziedziczą z elementu nadrzędnego.',
    dialogElementFolderNote: (verb: string) => `„${verb}” nie dotyczy folderu — tylko elementów znajdujących się w nim.`,
    elementFolderDescSection: 'Elementy wewnątrz',
    naChip: 'Nd.',
    redirectMessageElement:
      'Uprawnienia Library (elementów) dla tej grupy użytkowników są zarządzane przez pakiet Advanced Permissions. Otwórz Edytor uprawnień Library w sekcji Użytkownicy, aby skonfigurować uprawnienia.',
    library_menuLabel: 'Edytor uprawnień Library',
    library_editorHeadline: 'Edytor uprawnień Library',
    library_accessViewerMenuLabel: 'Podgląd dostępu Library',
    library_accessViewerHeadline: 'Podgląd dostępu Library',
    library_nodeHeader: 'Element Library',
    library_root: 'Uprawnienia domyślne',
    library_selectRolePrompt: 'Wybierz grupę użytkowników, aby zarządzać jej uprawnieniami Library.',
    library_permissionsSaved: 'Uprawnienia Library zapisane.',
    library_notApplicableTitle: (verb: string) => `${verb} nie dotyczy folderów — można je nadal ustawić dla elementów znajdujących się wewnątrz.`,
    library_folderInheritLabel: 'Elementy wewnątrz (elementy podrzędne)',
    libraryInsertViewer_menuLabel: 'Podgląd wstawiania Library',
    libraryInsertViewer_headline: 'Podgląd wstawiania Library',
    libraryInsertViewer_intro: 'Pokazuje, które typy elementów Library może tworzyć grupa użytkowników lub użytkownik, rozstrzygnięte we wszystkich jego grupach. Kliknij wiersz, aby zobaczyć uzasadnienie.',
    elementTypePermissions_menuLabel: 'Uprawnienia typów elementów Library',
    elementTypePermissions_headline: 'Uprawnienia typów elementów Library',
    elementTypePermissions_intro: 'Określ, które typy elementów może tworzyć każda grupa użytkowników w Library. Typy elementów są domyślnie możliwe do utworzenia; ustaw Zezwól lub Odmów — z opcjonalnym nadpisaniem priorytetu — aby kontrolować, jak rozstrzygany jest wybór, gdy użytkownik należy do kilku grup.',
    elementTypePermissions_typeHeader: 'Typ elementu',
    elementTypePermissions_verbCreate: 'Twórz w Library',
    elementTypePermissions_noTypes: 'Nie znaleziono typów elementów Library. Oznacz typ dokumentu jako typ elementu i włącz „Zezwól w Library”.',
    elementType_dialogHeadline: (type: string) => `Uprawnienie do tworzenia ‘${type}’ w Library`,
    elementType_inheritLabel: 'Nie ustawiono (domyślnie dozwolone)',
    elementType_allowLabel: 'Zezwól (możliwe do utworzenia w Library)',
    elementType_denyLabel: 'Odmów (ukryte w Library)',
    elementType_previewInherit: 'Brak jawnej reguły. Ten typ elementu jest domyślnie możliwy do utworzenia w Library.',
    elementType_previewSet: (action: string) => `${action} tworzenie tego typu elementu w Library.`,
  },
} satisfies UmbLocalizationDictionary;
