import type { UmbLocalizationDictionary } from '@umbraco-cms/backoffice/localization-api';

export default {
  uap: {
    // ── Navigering ────────────────────────────────────────────────────────
    sectionLabel: 'Avancerade behörigheter',
    editorsSectionLabel: 'Redigerare',
    viewersSectionLabel: 'Visningar',
    permissionsEditor: 'Redigerare för innehållsbehörigheter',
    accessViewer: 'Åtkomstvisning',

    // ── Allmänt ──────────────────────────────────────────────────────────
    roleLabel: 'Användargrupp',
    rolePlaceholder: '— Välj en användargrupp —',
    userLabel: 'Användare',
    saveChanges: 'Spara ändringar',
    discard: 'Ignorera',
    cancel: 'Avbryt',
    apply: 'Verkställ',
    close: 'Stäng',
    inherit: 'Ärv',
    allow: 'Tillåt',
    deny: 'Neka',
    umbracoUsers: 'Alla användare',

    // ── Behörighetsredigerare ─────────────────────────────────────────────
    editorHeadline: 'Redigerare för innehållsbehörigheter',
    selectRolePrompt: 'Välj en användargrupp ovan för att hantera dess behörigheter.',
    permissionsSaved: 'Behörigheter sparade.',
    saveFailed: (error: string) => `Sparandet misslyckades: ${error}`,
    contentNodeHeader: 'Innehållsnod',
    contentRoot: 'Standardbehörigheter',
    expand: 'Visa',
    collapse: 'Dölj',

    // ── Behörighetsdialog ───────────────────────────────────────────────
    dialogHeadline: (verb: string, nodeName: string) => `Ställ in ${verb}-behörighet för ‘${nodeName}’`,
    descendantsSection: 'Underordnade noder (om avvikande)',
    dialogInstructions: 'Ställ in behörigheten för denna nod. Som standard gäller detta även alla underordnade noder. Använd “Underordnade noder (om avvikande)” för att ställa in en annan behörighet för underordnade noder.',
    virtualRootInherit: 'Inte angiven (ta bort post)',
    virtualRootAllow: 'Tillåt (allt innehåll)',
    virtualRootDeny: 'Neka (allt innehåll)',
    dialogResult: 'Resultat',
    previewBothInherit: 'Ingen behörighet angiven. Ärvs från överordnad nod.',
    previewUniform: (action: string) => `${action} på denna nod och alla underordnade noder.`,
    previewNodeOnly: (action: string) => `${action} endast på denna nod. Underordnade noder påverkas inte av denna regel.`,
    previewDescOnly: (action: string) => `Ingen explicit behörighet på denna nod. ${action} på alla underordnade noder.`,
    previewSplit: (nodeAction: string, descAction: string) => `${nodeAction} på denna nod. ${descAction} på alla underordnade noder.`,
    previewVirtualInherit: 'Ingen standardbehörighet angiven.',
    previewVirtualSet: (action: string) => `${action} som standard för allt innehåll.`,
    previewPriorityNode: 'Prioritetsåsidosättning är angiven på denna nod.',
    previewPriorityDesc: 'Prioritetsåsidosättning är angiven på underordnade noder.',
    previewPriorityBoth: 'Prioritetsåsidosättning är angiven.',

    // ── Prioritetsåsidosättning ─────────────────────────────────────
    priorityOverride: 'Prioritetsåsidosättning',
    priorityOverrideTooltip: (permission: string, nodeName: string) =>
      `En användare kan tillhöra flera användargrupper. Normalt följer den effektiva behörigheten en fast prioritetsordning. Genom att kryssa i denna ruta åsidosätts den ordningen, så att inställningen “${permission}” som du väljer här nästan alltid blir resultatet för “${nodeName}”, oavsett användarens övriga grupper. Använd sparsamt.`,
    priorityOverrideBadgeTitle: 'Prioritetsåsidosättning är angiven på denna post',
    priorityOverrideWonTitle: 'Löst via prioritetsåsidosättning',
    priorityOverrideSuppressedHeader: 'Prioritetsåsidosättning ändrade resultatet',
    priorityOverrideSuppressedHint: 'Utan den skulle resultatet ha blivit:',

    // ── Åtkomstvisning ──────────────────────────────────────────────────
    viewerHeadline: 'Åtkomstvisning',
    byRole: 'Per användargrupp',
    byUser: 'Per användare',
    chooseRole: 'Välj användargrupp',
    chooseUser: 'Välj användare',
    selectSubjectPrompt: 'Välj en användargrupp eller användare för att visa effektiva behörigheter.',
    legendAllow: 'Tillåt',
    legendDeny: 'Neka',
    clickForReasoning: (label: string) => `${label} — klicka för motivering`,
    subjectOr: 'eller',

    // ── Modal för användargruppsval ───────────────────────────────────────
    rolePickerHeadline: 'Välj en användargrupp',
    rolePickerFilter: 'Skriv för att filtrera…',
    rolePickerNoResults: 'Inga användargrupper matchar filtret.',
    rolePickerNameHeader: 'Användargrupp',

    // ── Modal för användarval ───────────────────────────────────────────
    userPickerHeadline: 'Välj en användare',
    userPickerFilter: 'Skriv för att filtrera…',
    userPickerNoResults: 'Inga användare matchar filtret.',
    userPickerNameHeader: 'Användare',

    // ── Motiveringsdialog ──────────────────────────────────────────────────
    reasoningHeadline: (verb: string, nodeName: string) => `${verb}-behörighet för “${nodeName}”`,
    effectiveAllowed: (subject: string, verb: string, nodeName: string) =>
      `${subject} har beviljats ${verb}-behörighet för “${nodeName}”.`,
    effectiveDenied: (subject: string, verb: string, nodeName: string) =>
      `${subject} har nekats ${verb}-behörighet för “${nodeName}”.`,
    dialogSecurityHeader: 'Säkerhet',
    defaultPermissions: 'Standardbehörigheter',
    determiningEntry: 'Denna post har företräde',
    noReasoningData: 'Inga behörighetsdata tillgängliga för detta verb.',
    defaultAllowNote: 'Inga behörigheter är angivna, detta tillåts som standard.',
    defaultDenyNote: 'Inga behörigheter är angivna, detta nekas som standard.',

    // ── Omdirigeringsmeddelande för granulära behörigheter ───────────────
    redirectMessage:
      'Dokumentbehörigheter för denna användargrupp hanteras av paketet Advanced Permissions. Öppna behörighetsredigeraren i sektionen Användare för att konfigurera behörigheter.',

    // ── Dokumenttypsbehörigheter ──────────────────────────────────────────
    role: 'Användargrupp',
    pickRole: 'Välj användargrupp',
    user: 'Användare',
    pickUser: 'Välj användare',
    node: 'Nod',
    pickNode: 'Välj nod',
    state: 'Status',
    scope: 'Omfattning',
    scope_thisNodeOnly: 'Endast denna nod',
    scope_thisNodeAndDescendants: 'Denna nod och underordnade',
    scope_descendantsOnly: 'Endast underordnade',

    docTypePermissions_menuLabel: 'Redigerare för dokumenttypsbehörigheter',
    docTypePermissions_insertOptionsMenuLabel: 'Visning av infogningsalternativ',
    docTypePermissions_workspaceTitle: 'Redigerare för dokumenttypsbehörigheter',
    docTypePermissions_auditTitle: 'Visning av infogningsalternativ',
    docTypePermissions_allDocTypes: 'Alla dokumenttyper',
    docTypePermissions_verbInsert: 'Infoga',
    docTypePermissions_documentType: 'Dokumenttyp',
    chooseDocType: 'Välj dokumenttyp',
    notAnInsertOption: 'Denna dokumenttyp är för närvarande inte ett infogningsalternativ på denna nod.',
    notAnInsertOptionAllowedNote: 'Denna dokumenttyp är inte ett infogningsalternativ på denna nod, men skulle annars tillåtas.',
    notAnInsertOptionDeniedNote: 'Denna dokumenttyp är inte ett infogningsalternativ på denna nod, men skulle annars nekas.',
    docTypePermissions_pickDocType: '— Välj en dokumenttyp —',
    docTypePermissions_pickToStart: 'Välj en användargrupp och dokumenttyp för att börja.',
    docTypePermissions_defaultRowLabel: 'Standard (gäller överallt)',
    docTypePermissions_pendingNodeLabel: '(osparad nod)',
    docTypePermissions_addScopeNode: 'Lägg till omfattningsåsidosättning',
    docTypePermissions_notSet: 'Inte angiven',
    docTypePermissions_noResults: 'Inga dokumenttyper hittades.',
    docTypePermissions_useRoot: 'Använd rot',
    docTypePermissions_pickedNode: 'Nod:',
    docTypePermissions_rootLevel: 'Rotnivå',
    docTypePermissions_reasoning: 'Motivering',
    docTypePermissions_defaultAllow: 'Tillåts som standard',
    docTypePermissions_viaDefault: 'från standardrad',
    // -- i18n completion (machine-translated, pending review) --
    help_contentPermissions_description: 'Hantera Tillåt/Neka-behörigheter per användargrupp i ditt innehållsträd.',
    help_accessViewer_description: 'Se de effektiva behörigheter en användare eller grupp har vid valfri nod, med fullständig motivering.',
    help_docTypePermissions_description: 'Bestäm vilka dokumenttyper varje användargrupp kan skapa, och var.',
    help_insertOptions_description: 'Granska vilka dokumenttyper en användare eller användargrupp kan skapa vid varje nod.',
    help_libraryPermissions_description: 'Hantera Tillåt/Neka-behörigheter per användargrupp i biblioteksträdet.',
    help_elementTypePermissions_description: 'Styr vilka elementtyper varje användargrupp kan använda i biblioteket.',
    help_libraryAccessViewer_description: 'Se de effektiva biblioteksbehörigheter en användare eller användargrupp har vid varje nod.',
    help_libraryInsertViewer_description: 'Granska vilka elementtyper en användare eller användargrupp kan infoga i biblioteket.',
    help_learnMore: 'Läs mer',
    help_modalTitle: 'Hjälp',
    help_tabAbout: 'Om denna sida',
    help_tabConcepts: 'Begrepp',
    help_concept_scope_tip: 'Omfattning styr hur långt en regel når: denna nod, denna nod och dess underordnade, eller endast underordnade.',
    help_concept_priorityOverride_tip: 'Prioritetsåsidosättning tvingar denna post att vinna över den normala lösningsordningen.',
    help_concept_allowDeny_tip: 'Tillåt beviljar behörigheten, Neka återkallar den, och om den lämnas oangiven ärvs den från närmaste överordnade nod.',
    help_concept_reasoning_tip: 'Klicka på valfri cell för att se exakt hur behörigheten löstes.',
    previewElementFolderSet: (action: string) => `Gäller inte denna mapp. ${action} på elementen inuti den.`,
    previewElementFolderInherit: 'Gäller inte denna mapp. Elementen inuti den ärver från sin överordnade nod.',
    dialogElementFolderNote: (verb: string) => `“${verb}” gäller inte en mapp — endast elementen inuti den.`,
    elementFolderDescSection: 'Element inuti',
    naChip: 'Ej tillämpligt',
    redirectMessageElement:
      'Bibliotekets (element-)behörigheter för denna användargrupp hanteras av paketet Advanced Permissions. Öppna redigeraren för biblioteksbehörigheter i sektionen Användare för att konfigurera behörigheter.',
    library_menuLabel: 'Redigerare för biblioteksbehörigheter',
    library_editorHeadline: 'Redigerare för biblioteksbehörigheter',
    library_accessViewerMenuLabel: 'Åtkomstvisning för bibliotek',
    library_accessViewerHeadline: 'Åtkomstvisning för bibliotek',
    library_nodeHeader: 'Biblioteksobjekt',
    library_root: 'Standardbehörigheter',
    library_selectRolePrompt: 'Välj en användargrupp för att hantera dess biblioteksbehörigheter.',
    library_permissionsSaved: 'Biblioteksbehörigheter sparade.',
    library_notApplicableTitle: (verb: string) => `${verb} gäller inte mappar — den kan ändå anges för objekten inuti.`,
    library_folderInheritLabel: 'Objekt inuti (underordnade)',
    libraryInsertViewer_menuLabel: 'Visning av biblioteksinfogning',
    libraryInsertViewer_headline: 'Visning av biblioteksinfogning',
    libraryInsertViewer_intro: 'Visar vilka biblioteks-elementtyper en användargrupp eller användare kan skapa, löst över alla deras grupper. Klicka på en rad för att se motiveringen.',
    elementTypePermissions_menuLabel: 'Behörigheter för biblioteks-elementtyper',
    elementTypePermissions_headline: 'Behörigheter för biblioteks-elementtyper',
    elementTypePermissions_intro: 'Styr vilka elementtyper varje användargrupp kan skapa i biblioteket. Elementtyper är skapbara som standard; ange Tillåt eller Neka — med en valfri prioritetsåsidosättning — för att styra hur valet löses när en användare tillhör flera grupper.',
    elementTypePermissions_typeHeader: 'Elementtyp',
    elementTypePermissions_verbCreate: 'Skapa i biblioteket',
    elementTypePermissions_noTypes: 'Inga biblioteks-elementtyper hittades. Markera en dokumenttyp som en elementtyp och aktivera “Tillåt i bibliotek”.',
    elementType_dialogHeadline: (type: string) => `Skapa-behörighet för ‘${type}’ i biblioteket`,
    elementType_inheritLabel: 'Inte angiven (tillåts som standard)',
    elementType_allowLabel: 'Tillåt (skapbar i biblioteket)',
    elementType_denyLabel: 'Neka (dold från biblioteket)',
    elementType_previewInherit: 'Ingen explicit regel. Denna elementtyp är skapbar i biblioteket som standard.',
    elementType_previewSet: (action: string) => `${action} att skapa denna elementtyp i biblioteket.`,
  },
} satisfies UmbLocalizationDictionary;
