import type { UmbLocalizationDictionary } from '@umbraco-cms/backoffice/localization-api';

export default {
  uap: {
    // ── Gezinme ───────────────────────────────────────────────────────────
    sectionLabel: 'Gelişmiş İzinler',
    group_content: 'İçerik İzinleri',
    group_documentTypes: 'Belge Türü İzinleri',
    group_library: 'Library İzinleri',
    group_libraryElementTypes: 'Library Öğe Türü İzinleri',
    menuItem_permissionsEditor: 'İzin Düzenleyicisi',
    menuItem_accessViewer: 'Erişim Görüntüleyici',
    editorsSectionLabel: 'Düzenleyiciler',
    viewersSectionLabel: 'Görüntüleyiciler',
    permissionsEditor: 'İçerik İzinleri Düzenleyicisi',
    accessViewer: 'Erişim Görüntüleyici',

    // ── Genel ─────────────────────────────────────────────────────────────
    roleLabel: 'Kullanıcı Grubu',
    rolePlaceholder: '— Bir kullanıcı grubu seçin —',
    userLabel: 'Kullanıcı',
    saveChanges: 'Değişiklikleri Kaydet',
    discard: 'Gözden çıkar',
    cancel: 'İptal',
    apply: 'Uygula',
    close: 'Kapat',
    inherit: 'Devral',
    allow: 'İzin ver',
    deny: 'Reddet',
    umbracoUsers: 'Tüm Kullanıcılar',

    // ── İzin Düzenleyicisi ───────────────────────────────────────────────
    editorHeadline: 'İçerik İzinleri Düzenleyicisi',
    selectRolePrompt: 'İzinlerini yönetmek için yukarıdan bir kullanıcı grubu seçin.',
    permissionsSaved: 'İzinler kaydedildi.',
    saveFailed: (error: string) => `Kaydetme başarısız: ${error}`,
    contentNodeHeader: 'İçerik Düğümü',
    contentRoot: 'Varsayılan izinler',
    expand: 'Genişlet',
    collapse: 'Daralt',

    // ── İzin iletişim kutusu ──────────────────────────────────────────────
    dialogHeadline: (verb: string, nodeName: string) => `‘${nodeName}’ için ${verb} iznini ayarlayın`,
    descendantsSection: 'Alt düğümler (farklıysa)',
    dialogInstructions: 'Bu düğüm için izni ayarlayın. Varsayılan olarak bu, tüm alt düğümler için de geçerlidir. Alt düğümler için farklı bir izin ayarlamak üzere “Alt düğümler (farklıysa)” seçeneğini kullanın.',
    virtualRootInherit: 'Ayarlanmadı (kaydı kaldır)',
    virtualRootAllow: 'İzin ver (tüm içerik)',
    virtualRootDeny: 'Reddet (tüm içerik)',
    dialogResult: 'Sonuç',
    previewBothInherit: 'İzin ayarlanmadı. Üst düğümden devralır.',
    previewUniform: (action: string) => `Bu düğümde ve tüm alt düğümlerde ${action}.`,
    previewNodeOnly: (action: string) => `Yalnızca bu düğümde ${action}. Alt düğümler bu kuraldan etkilenmez.`,
    previewDescOnly: (action: string) => `Bu düğümde açık bir izin yok. Tüm alt düğümlerde ${action}.`,
    previewSplit: (nodeAction: string, descAction: string) => `Bu düğümde ${nodeAction}. Tüm alt düğümlerde ${descAction}.`,
    previewVirtualInherit: 'Varsayılan izin ayarlanmadı.',
    previewVirtualSet: (action: string) => `Tüm içerik için varsayılan olarak ${action}.`,
    previewPriorityNode: 'Öncelik geçersiz kılma bu düğümde ayarlı.',
    previewPriorityDesc: 'Öncelik geçersiz kılma alt düğümlerde ayarlı.',
    previewPriorityBoth: 'Öncelik geçersiz kılma ayarlı.',

    // ── Öncelik geçersiz kılma ────────────────────────────────────────
    priorityOverride: 'Öncelik geçersiz kılma',
    priorityOverrideTooltip: (permission: string, nodeName: string) =>
      `Bir kullanıcı birden fazla kullanıcı grubuna ait olabilir. Normalde etkin izin, sabit bir öncelik sırasını izler. Bu kutuyu işaretlemek bu sırayı geçersiz kılar; böylece burada seçtiğiniz “${permission}” ayarı, kullanıcının diğer gruplarından bağımsız olarak “${nodeName}” için neredeyse her zaman sonuç olur. Dikkatli kullanın.`,
    priorityOverrideBadgeTitle: 'Bu kayıtta öncelik geçersiz kılma ayarlı',
    priorityOverrideWonTitle: 'Öncelik geçersiz kılma ile çözüldü',
    priorityOverrideSuppressedHeader: 'Öncelik geçersiz kılma sonucu değiştirdi',
    priorityOverrideSuppressedHint: 'Bu olmadan sonuç şöyle olurdu:',

    // ── Erişim Görüntüleyici ──────────────────────────────────────────────
    viewerHeadline: 'İçerik Erişim Görüntüleyici',
    byRole: 'Kullanıcı grubuna göre',
    byUser: 'Kullanıcıya göre',
    chooseRole: 'Kullanıcı grubu seçin',
    chooseUser: 'Kullanıcı seçin',
    selectSubjectPrompt: 'Etkin izinleri görüntülemek için bir kullanıcı grubu veya kullanıcı seçin.',
    legendAllow: 'İzin ver',
    legendDeny: 'Reddet',
    clickForReasoning: (label: string) => `${label} — gerekçe için tıklayın`,
    subjectOr: 'veya',

    // ── Kullanıcı grubu seçme penceresi ───────────────────────────────────
    rolePickerHeadline: 'Bir kullanıcı grubu seçin',
    rolePickerFilter: 'Filtrelemek için yazın…',
    rolePickerNoResults: 'Filtreyle eşleşen kullanıcı grubu yok.',
    rolePickerNameHeader: 'Kullanıcı Grubu',

    // ── Kullanıcı seçme penceresi ─────────────────────────────────────────
    userPickerHeadline: 'Bir kullanıcı seçin',
    userPickerFilter: 'Filtrelemek için yazın…',
    userPickerNoResults: 'Filtreyle eşleşen kullanıcı yok.',
    userPickerNameHeader: 'Kullanıcı',

    // ── Gerekçe iletişim kutusu ───────────────────────────────────────────
    reasoningHeadline: (verb: string, nodeName: string) => `“${nodeName}” için ${verb} izni`,
    effectiveAllowed: (subject: string, verb: string, nodeName: string) =>
      `${subject} için “${nodeName}” öğesinde ${verb} iznine izin verildi.`,
    effectiveDenied: (subject: string, verb: string, nodeName: string) =>
      `${subject} için “${nodeName}” öğesinde ${verb} izni reddedildi.`,
    dialogSecurityHeader: 'Güvenlik',
    defaultPermissions: 'Varsayılan izinler',
    determiningEntry: 'Bu kayıt önceliklidir',
    noReasoningData: 'Bu eylem için izin verisi yok.',
    defaultAllowNote: 'Hiçbir izin ayarlanmadı, buna varsayılan olarak izin verilir.',
    defaultDenyNote: 'Hiçbir izin ayarlanmadı, bu varsayılan olarak reddedilir.',

    // ── Ayrıntılı izinler yönlendirme mesajı ──────────────────────────────
    redirectMessage:
      'Bu kullanıcı grubu için belge izinleri Advanced Permissions paketi tarafından yönetilir. İzinleri yapılandırmak için Kullanıcılar bölümündeki İçerik İzinleri Düzenleyicisini açın.',

    // ── Belge Türü İzinleri ───────────────────────────────────────────────
    role: 'Kullanıcı Grubu',
    pickRole: 'Kullanıcı grubu seçin',
    user: 'Kullanıcı',
    pickUser: 'Kullanıcı seçin',
    node: 'Düğüm',
    pickNode: 'Düğüm seçin',
    state: 'Durum',
    scope: 'Kapsam',
    scope_thisNodeOnly: 'Yalnızca bu düğüm',
    scope_thisNodeAndDescendants: 'Bu düğüm ve alt düğümler',
    scope_descendantsOnly: 'Yalnızca alt düğümler',

    docTypePermissions_menuLabel: 'Belge Türü İzinleri Düzenleyicisi',
    docTypePermissions_insertOptionsMenuLabel: 'Ekleme Seçenekleri Görüntüleyici',
    docTypePermissions_workspaceTitle: 'Belge Türü İzinleri Düzenleyicisi',
    docTypePermissions_auditTitle: 'Belge Türü Erişim Görüntüleyici',
    docTypePermissions_allDocTypes: 'Tüm belge türleri',
    docTypePermissions_verbInsert: 'Ekle',
    docTypePermissions_documentType: 'Belge Türü',
    chooseDocType: 'Belge türü seçin',
    notAnInsertOption: 'Bu belge türü şu anda bu düğümde bir ekleme seçeneği değil.',
    notAnInsertOptionAllowedNote: 'Bu belge türü bu düğümde bir ekleme seçeneği değil, ancak aksi takdirde izin verilirdi.',
    notAnInsertOptionDeniedNote: 'Bu belge türü bu düğümde bir ekleme seçeneği değil, ancak aksi takdirde reddedilirdi.',
    docTypePermissions_pickDocType: '— Bir belge türü seçin —',
    docTypePermissions_pickToStart: 'Başlamak için bir kullanıcı grubu ve belge türü seçin.',
    docTypePermissions_defaultRowLabel: 'Varsayılan (her yerde geçerli)',
    docTypePermissions_pendingNodeLabel: '(kaydedilmemiş düğüm)',
    docTypePermissions_addScopeNode: 'Kapsam geçersiz kılma ekle',
    docTypePermissions_notSet: 'Ayarlanmadı',
    docTypePermissions_noResults: 'Belge türü bulunamadı.',
    docTypePermissions_useRoot: 'Kökü kullan',
    docTypePermissions_pickedNode: 'Düğüm:',
    docTypePermissions_rootLevel: 'Kök düzeyi',
    docTypePermissions_reasoning: 'Gerekçe',
    docTypePermissions_defaultAllow: 'Varsayılan olarak izin verildi',
    docTypePermissions_viaDefault: 'varsayılan satırdan',
    // -- i18n completion (machine-translated, pending review) --
    help_contentPermissions_description: 'İçerik ağacınız genelinde her kullanıcı grubu için İzin ver/Reddet izinlerini yönetin.',
    help_accessViewer_description: 'Bir kullanıcının veya grubun herhangi bir düğümde sahip olduğu etkin izinleri, tam gerekçesiyle birlikte görün.',
    help_docTypePermissions_description: 'Her kullanıcı grubunun hangi belge türlerini ve nerede oluşturabileceğine karar verin.',
    help_insertOptions_description: 'Bir kullanıcının veya kullanıcı grubunun her düğümde hangi belge türlerini oluşturabileceğini denetleyin.',
    help_libraryPermissions_description: 'Library ağacı genelinde her kullanıcı grubu için İzin ver/Reddet izinlerini yönetin.',
    help_elementTypePermissions_description: 'Her kullanıcı grubunun Library içinde hangi öğe türlerini kullanabileceğini denetleyin.',
    help_libraryAccessViewer_description: 'Bir kullanıcının veya kullanıcı grubunun her düğümde sahip olduğu etkin Library izinlerini görün.',
    help_libraryInsertViewer_description: 'Bir kullanıcının veya kullanıcı grubunun Library içinde hangi öğe türlerini ekleyebileceğini denetleyin.',
    help_learnMore: 'Daha fazla bilgi',
    help_modalTitle: 'Yardım',
    help_tabAbout: 'Bu sayfa hakkında',
    help_tabConcepts: 'Kavramlar',
    help_concept_scope_tip: 'Kapsam, bir kuralın ne kadar uzağa eriştiğini denetler: bu düğüm, bu düğüm ve alt düğümleri veya yalnızca alt düğümler.',
    help_concept_priorityOverride_tip: 'Öncelik geçersiz kılma, bu kaydı normal çözümleme sırasına göre öne çıkmaya zorlar.',
    help_concept_allowDeny_tip: 'İzin ver iznini verir, Reddet onu geri alır ve ayarlanmadan bırakmak en yakın üst düğümden devralır.',
    help_concept_reasoning_tip: 'İznin tam olarak nasıl çözümlendiğini görmek için herhangi bir hücreye tıklayın.',
    previewElementFolderSet: (action: string) => `Bu klasör için geçerli değildir. İçindeki öğelerde ${action}.`,
    previewElementFolderInherit: 'Bu klasör için geçerli değildir. İçindeki öğeler üst düğümlerinden devralır.',
    dialogElementFolderNote: (verb: string) => `“${verb}” bir klasör için geçerli değildir — yalnızca içindeki öğeler için geçerlidir.`,
    elementFolderDescSection: 'İçindeki öğeler',
    naChip: 'Yok',
    redirectMessageElement:
      'Bu kullanıcı grubu için Library (öğe) izinleri Advanced Permissions paketi tarafından yönetilir. İzinleri yapılandırmak için Kullanıcılar bölümündeki Library İzin Düzenleyicisini açın.',
    library_menuLabel: 'Library İzin Düzenleyicisi',
    library_editorHeadline: 'Library İzin Düzenleyicisi',
    library_accessViewerMenuLabel: 'Library Erişim Görüntüleyici',
    library_accessViewerHeadline: 'Library Erişim Görüntüleyici',
    library_nodeHeader: 'Library Öğesi',
    library_root: 'Varsayılan izinler',
    library_selectRolePrompt: 'Library izinlerini yönetmek için bir kullanıcı grubu seçin.',
    library_permissionsSaved: 'Library izinleri kaydedildi.',
    library_notApplicableTitle: (verb: string) => `${verb} klasörler için geçerli değildir — yine de içindeki öğeler için ayarlanabilir.`,
    library_folderInheritLabel: 'İçindeki öğeler (alt düğümler)',
    libraryInsertViewer_menuLabel: 'Library Ekleme Görüntüleyici',
    libraryInsertViewer_headline: 'Library Öğe Türü Erişim Görüntüleyici',
    libraryInsertViewer_intro: 'Bir kullanıcı grubunun veya kullanıcının hangi Library öğe türlerini oluşturabileceğini, tüm gruplarına göre çözümlenmiş olarak gösterir. Gerekçeyi görmek için bir satıra tıklayın.',
    elementTypePermissions_menuLabel: 'Library Öğe Türü İzinleri',
    elementTypePermissions_headline: 'Library Öğe Türü İzinleri Düzenleyicisi',
    elementTypePermissions_intro: 'Her kullanıcı grubunun Library içinde hangi öğe türlerini oluşturabileceğini denetleyin. Öğe türleri varsayılan olarak oluşturulabilir; bir kullanıcı birden fazla gruba ait olduğunda seçimin nasıl çözümleneceğini denetlemek için İzin ver veya Reddet ayarlayın — isteğe bağlı bir öncelik geçersiz kılmasıyla birlikte.',
    elementTypePermissions_typeHeader: 'Öğe Türü',
    elementTypePermissions_verbCreate: 'Library içinde oluştur',
    elementTypePermissions_noTypes: 'Library öğe türü bulunamadı. Bir belge türünü öğe türü olarak işaretleyin ve “Library içinde izin ver” seçeneğini etkinleştirin.',
    elementType_dialogHeadline: (type: string) => `Library içinde ‘${type}’ için oluşturma izni`,
    elementType_inheritLabel: 'Ayarlanmadı (varsayılan olarak izin verildi)',
    elementType_allowLabel: 'İzin ver (Library içinde oluşturulabilir)',
    elementType_denyLabel: 'Reddet (Library’den gizli)',
    elementType_previewInherit: 'Açık bir kural yok. Bu öğe türü varsayılan olarak Library içinde oluşturulabilir.',
    elementType_previewSet: (action: string) => `Library içinde bu öğe türünü oluşturmaya ${action}.`,
  },
} satisfies UmbLocalizationDictionary;
