import type { UmbLocalizationDictionary } from '@umbraco-cms/backoffice/localization-api';

export default {
  uap: {
    // ── Navigation ────────────────────────────────────────────────────────
    sectionLabel: 'Phân quyền nâng cao',
    group_content: 'Quyền nội dung',
    group_documentTypes: 'Quyền loại tài liệu',
    group_library: 'Quyền Library',
    group_libraryElementTypes: 'Quyền loại phần tử Library',
    menuItem_permissionsEditor: 'Trình chỉnh sửa quyền',
    menuItem_accessViewer: 'Trình xem quyền truy cập',
    editorsSectionLabel: 'Trình chỉnh sửa',
    viewersSectionLabel: 'Trình xem',
    permissionsEditor: 'Trình chỉnh sửa quyền nội dung',
    accessViewer: 'Trình xem quyền truy cập',

    // ── Common ────────────────────────────────────────────────────────────
    roleLabel: 'Nhóm người dùng',
    rolePlaceholder: '— Chọn một nhóm người dùng —',
    userLabel: 'Người dùng',
    saveChanges: 'Lưu thay đổi',
    discard: 'Bỏ',
    cancel: 'Hủy',
    apply: 'Áp dụng',
    close: 'Đóng',
    inherit: 'Kế thừa',
    allow: 'Cho phép',
    deny: 'Từ chối',
    umbracoUsers: 'Tất cả người dùng',

    // ── Permissions Editor ───────────────────────────────────────────────
    editorHeadline: 'Trình chỉnh sửa quyền nội dung',
    selectRolePrompt: 'Chọn một nhóm người dùng ở trên để quản lý quyền của nhóm đó.',
    permissionsSaved: 'Đã lưu quyền.',
    saveFailed: (error: string) => `Lưu thất bại: ${error}`,
    contentNodeHeader: 'Nút nội dung',
    contentRoot: 'Quyền mặc định',
    expand: 'Mở rộng',
    collapse: 'Thu gọn',

    // ── Permission dialog ─────────────────────────────────────────────────
    dialogHeadline: (verb: string, nodeName: string) => `Đặt quyền ${verb} cho ‘${nodeName}’`,
    descendantsSection: 'Các nút con cháu (nếu khác)',
    dialogInstructions: 'Đặt quyền cho nút này. Theo mặc định, quyền này cũng áp dụng cho tất cả các nút con cháu. Sử dụng “Các nút con cháu (nếu khác)” để đặt một quyền khác cho các nút con cháu.',
    virtualRootInherit: 'Không đặt (xóa mục)',
    virtualRootAllow: 'Cho phép (tất cả nội dung)',
    virtualRootDeny: 'Từ chối (tất cả nội dung)',
    dialogResult: 'Kết quả',
    previewBothInherit: 'Chưa đặt quyền. Kế thừa từ nút cha.',
    previewUniform: (action: string) => `${action} trên nút này và tất cả các nút con cháu.`,
    previewNodeOnly: (action: string) => `${action} chỉ trên nút này. Các nút con cháu không bị ảnh hưởng bởi quy tắc này.`,
    previewDescOnly: (action: string) => `Không có quyền rõ ràng trên nút này. ${action} trên tất cả các nút con cháu.`,
    previewSplit: (nodeAction: string, descAction: string) => `${nodeAction} trên nút này. ${descAction} trên tất cả các nút con cháu.`,
    previewVirtualInherit: 'Chưa đặt quyền mặc định.',
    previewVirtualSet: (action: string) => `${action} theo mặc định cho tất cả nội dung.`,
    previewPriorityNode: 'Ghi đè ưu tiên được đặt trên nút này.',
    previewPriorityDesc: 'Ghi đè ưu tiên được đặt trên các nút con cháu.',
    previewPriorityBoth: 'Ghi đè ưu tiên đã được đặt.',

    // ── Priority override ─────────────────────────────────────────────────
    priorityOverride: 'Ghi đè ưu tiên',
    priorityOverrideTooltip: (permission: string, nodeName: string) =>
      `Một người dùng có thể thuộc nhiều nhóm người dùng. Thông thường, quyền hiệu lực tuân theo một thứ tự ưu tiên cố định. Đánh dấu vào ô này sẽ ghi đè thứ tự đó, vì vậy cài đặt “${permission}” mà bạn chọn ở đây gần như luôn trở thành kết quả cho “${nodeName}”, bất kể các nhóm khác của người dùng. Hãy sử dụng một cách thận trọng.`,
    priorityOverrideBadgeTitle: 'Ghi đè ưu tiên được đặt trên mục này',
    priorityOverrideWonTitle: 'Được giải quyết qua ghi đè ưu tiên',
    priorityOverrideSuppressedHeader: 'Ghi đè ưu tiên đã thay đổi kết quả',
    priorityOverrideSuppressedHint: 'Nếu không có nó, kết quả sẽ là:',

    // ── Access Viewer ─────────────────────────────────────────────────────
    viewerHeadline: 'Trình xem quyền truy cập nội dung',
    byRole: 'Theo nhóm người dùng',
    byUser: 'Theo người dùng',
    chooseRole: 'Chọn nhóm người dùng',
    chooseUser: 'Chọn người dùng',
    selectSubjectPrompt: 'Chọn một nhóm người dùng hoặc người dùng để xem quyền hiệu lực.',
    legendAllow: 'Cho phép',
    legendDeny: 'Từ chối',
    clickForReasoning: (label: string) => `${label} — nhấp để xem lý giải`,
    subjectOr: 'hoặc',

    // ── Role picker modal ─────────────────────────────────────────────────
    rolePickerHeadline: 'Chọn một nhóm người dùng',
    rolePickerFilter: 'Nhập để lọc…',
    rolePickerNoResults: 'Không có nhóm người dùng nào khớp với bộ lọc.',
    rolePickerNameHeader: 'Nhóm người dùng',

    // ── User picker modal ─────────────────────────────────────────────────
    userPickerHeadline: 'Chọn một người dùng',
    userPickerFilter: 'Nhập để lọc…',
    userPickerNoResults: 'Không có người dùng nào khớp với bộ lọc.',
    userPickerNameHeader: 'Người dùng',

    // ── Reasoning dialog ──────────────────────────────────────────────────
    reasoningHeadline: (verb: string, nodeName: string) => `Quyền ${verb} cho “${nodeName}”`,
    effectiveAllowed: (subject: string, verb: string, nodeName: string) =>
      `${subject} đã được cho phép quyền ${verb} cho “${nodeName}”.`,
    effectiveDenied: (subject: string, verb: string, nodeName: string) =>
      `${subject} đã bị từ chối quyền ${verb} cho “${nodeName}”.`,
    dialogSecurityHeader: 'Bảo mật',
    defaultPermissions: 'Quyền mặc định',
    determiningEntry: 'Mục này được ưu tiên',
    noReasoningData: 'Không có dữ liệu quyền nào cho động từ này.',
    defaultAllowNote: 'Không có quyền nào được đặt, điều này được cho phép theo mặc định.',
    defaultDenyNote: 'Không có quyền nào được đặt, điều này bị từ chối theo mặc định.',

    // ── Granular permission redirect ──────────────────────────────────────
    redirectMessage:
      'Quyền tài liệu cho nhóm người dùng này được quản lý bởi gói Advanced Permissions. Mở Trình chỉnh sửa quyền nội dung trong mục Người dùng để cấu hình quyền.',

    // ── Doc-Type Permissions ──────────────────────────────────────────────
    role: 'Nhóm người dùng',
    pickRole: 'Chọn nhóm người dùng',
    user: 'Người dùng',
    pickUser: 'Chọn người dùng',
    node: 'Nút',
    pickNode: 'Chọn nút',
    state: 'Trạng thái',
    scope: 'Phạm vi',
    scope_thisNodeOnly: 'Chỉ nút này',
    scope_thisNodeAndDescendants: 'Nút này và các nút con cháu',
    scope_descendantsOnly: 'Chỉ các nút con cháu',

    docTypePermissions_menuLabel: 'Trình chỉnh sửa quyền loại tài liệu',
    docTypePermissions_insertOptionsMenuLabel: 'Trình xem tùy chọn chèn',
    docTypePermissions_workspaceTitle: 'Trình chỉnh sửa quyền loại tài liệu',
    docTypePermissions_auditTitle: 'Trình xem quyền truy cập loại tài liệu',
    docTypePermissions_allDocTypes: 'Tất cả loại tài liệu',
    docTypePermissions_verbInsert: 'Chèn',
    docTypePermissions_documentType: 'Loại tài liệu',
    chooseDocType: 'Chọn loại tài liệu',
    notAnInsertOption: 'Loại tài liệu này hiện không phải là một tùy chọn chèn trên nút này.',
    notAnInsertOptionAllowedNote: 'Loại tài liệu này không phải là một tùy chọn chèn trên nút này, nhưng nếu khác thì sẽ được cho phép.',
    notAnInsertOptionDeniedNote: 'Loại tài liệu này không phải là một tùy chọn chèn trên nút này, nhưng nếu khác thì sẽ bị từ chối.',
    docTypePermissions_pickDocType: '— Chọn một loại tài liệu —',
    docTypePermissions_pickToStart: 'Chọn một nhóm người dùng và loại tài liệu để bắt đầu.',
    docTypePermissions_defaultRowLabel: 'Mặc định (áp dụng ở mọi nơi)',
    docTypePermissions_pendingNodeLabel: '(nút chưa lưu)',
    docTypePermissions_addScopeNode: 'Thêm ghi đè phạm vi',
    docTypePermissions_notSet: 'Chưa đặt',
    docTypePermissions_noResults: 'Không tìm thấy loại tài liệu nào.',
    docTypePermissions_useRoot: 'Dùng gốc',
    docTypePermissions_pickedNode: 'Nút:',
    docTypePermissions_rootLevel: 'Cấp gốc',
    docTypePermissions_reasoning: 'Lý giải',
    docTypePermissions_defaultAllow: 'Được cho phép theo mặc định',
    docTypePermissions_viaDefault: 'từ hàng mặc định',
    // -- i18n completion (machine-translated, pending review) --
    help_contentPermissions_description: 'Quản lý quyền Cho phép/Từ chối cho từng nhóm người dùng trên toàn bộ cây nội dung của bạn.',
    help_accessViewer_description: 'Xem quyền hiệu lực mà một người dùng hoặc nhóm có tại bất kỳ nút nào, kèm theo lý giải đầy đủ.',
    help_docTypePermissions_description: 'Quyết định loại tài liệu nào mà mỗi nhóm người dùng có thể tạo, và ở đâu.',
    help_insertOptions_description: 'Kiểm tra loại tài liệu nào mà một người dùng hoặc nhóm người dùng có thể tạo tại mỗi nút.',
    help_libraryPermissions_description: 'Quản lý quyền Cho phép/Từ chối cho từng nhóm người dùng trên toàn bộ cây Library.',
    help_elementTypePermissions_description: 'Kiểm soát loại phần tử nào mà mỗi nhóm người dùng có thể sử dụng trong Library.',
    help_libraryAccessViewer_description: 'Xem quyền Library hiệu lực mà một người dùng hoặc nhóm người dùng có tại mỗi nút.',
    help_libraryInsertViewer_description: 'Kiểm tra loại phần tử nào mà một người dùng hoặc nhóm người dùng có thể chèn trong Library.',
    help_learnMore: 'Tìm hiểu thêm',
    help_modalTitle: 'Trợ giúp',
    help_tabAbout: 'Về trang này',
    help_tabConcepts: 'Khái niệm',
    help_concept_scope_tip: 'Phạm vi kiểm soát mức độ áp dụng của một quy tắc: chỉ nút này, nút này và các nút con cháu của nó, hoặc chỉ các nút con cháu.',
    help_concept_priorityOverride_tip: 'Ghi đè ưu tiên buộc mục này thắng so với thứ tự giải quyết thông thường.',
    help_concept_allowDeny_tip: 'Cho phép cấp quyền, Từ chối thu hồi quyền, và để trống sẽ kế thừa từ nút tổ tiên gần nhất.',
    help_concept_reasoning_tip: 'Nhấp vào bất kỳ ô nào để xem chính xác quyền đã được giải quyết như thế nào.',
    previewElementFolderSet: (action: string) => `Không áp dụng cho thư mục này. ${action} trên các phần tử bên trong nó.`,
    previewElementFolderInherit: 'Không áp dụng cho thư mục này. Các phần tử bên trong nó kế thừa từ nút cha của chúng.',
    dialogElementFolderNote: (verb: string) => `“${verb}” không áp dụng cho một thư mục — chỉ áp dụng cho các phần tử bên trong nó.`,
    elementFolderDescSection: 'Các phần tử bên trong',
    naChip: 'Không áp dụng',
    redirectMessageElement:
      'Quyền Library (phần tử) cho nhóm người dùng này được quản lý bởi gói Advanced Permissions. Mở Trình chỉnh sửa quyền Library trong mục Người dùng để cấu hình quyền.',
    library_menuLabel: 'Trình chỉnh sửa quyền Library',
    library_editorHeadline: 'Trình chỉnh sửa quyền Library',
    library_accessViewerMenuLabel: 'Trình xem quyền truy cập Library',
    library_accessViewerHeadline: 'Trình xem quyền truy cập Library',
    library_nodeHeader: 'Mục Library',
    library_root: 'Quyền mặc định',
    library_selectRolePrompt: 'Chọn một nhóm người dùng để quản lý quyền Library của nhóm đó.',
    library_permissionsSaved: 'Đã lưu quyền Library.',
    library_notApplicableTitle: (verb: string) => `${verb} không áp dụng cho thư mục — vẫn có thể đặt cho các mục bên trong.`,
    library_folderInheritLabel: 'Các mục bên trong (nút con cháu)',
    libraryInsertViewer_menuLabel: 'Trình xem chèn Library',
    libraryInsertViewer_headline: 'Trình xem quyền truy cập loại phần tử Library',
    libraryInsertViewer_intro: 'Hiển thị loại phần tử Library nào mà một nhóm người dùng hoặc người dùng có thể tạo, được giải quyết trên tất cả các nhóm của họ. Nhấp vào một hàng để xem lý giải.',
    elementTypePermissions_menuLabel: 'Quyền loại phần tử Library',
    elementTypePermissions_headline: 'Trình chỉnh sửa quyền loại phần tử Library',
    elementTypePermissions_intro: 'Kiểm soát loại phần tử nào mà mỗi nhóm người dùng có thể tạo trong Library. Loại phần tử có thể tạo theo mặc định; đặt Cho phép hoặc Từ chối — kèm theo ghi đè ưu tiên tùy chọn — để kiểm soát cách lựa chọn được giải quyết khi một người dùng thuộc nhiều nhóm.',
    elementTypePermissions_typeHeader: 'Loại phần tử',
    elementTypePermissions_verbCreate: 'Tạo trong Library',
    elementTypePermissions_noTypes: 'Không tìm thấy loại phần tử Library nào. Đánh dấu một loại tài liệu là loại phần tử và bật “Cho phép trong Library”.',
    elementType_dialogHeadline: (type: string) => `Quyền tạo cho ‘${type}’ trong Library`,
    elementType_inheritLabel: 'Không đặt (được cho phép theo mặc định)',
    elementType_allowLabel: 'Cho phép (có thể tạo trong Library)',
    elementType_denyLabel: 'Từ chối (ẩn khỏi Library)',
    elementType_previewInherit: 'Không có quy tắc rõ ràng. Loại phần tử này có thể tạo trong Library theo mặc định.',
    elementType_previewSet: (action: string) => `${action} tạo loại phần tử này trong Library.`,
  },
} satisfies UmbLocalizationDictionary;
