import type { UmbLocalizationDictionary } from '@umbraco-cms/backoffice/localization-api';

export default {
  uap: {
    // ── 導覽 ──────────────────────────────────────────────────────────────
    sectionLabel: '進階權限',
    group_content: '內容權限',
    group_documentTypes: '文檔類型權限',
    group_library: 'Library 權限',
    group_libraryElementTypes: 'Library 元素類型權限',
    menuItem_permissionsEditor: '權限編輯器',
    menuItem_accessViewer: '存取檢視器',
    editorsSectionLabel: '編輯器',
    viewersSectionLabel: '檢視器',
    permissionsEditor: '內容權限編輯器',
    accessViewer: '存取檢視器',

    // ── 一般 ──────────────────────────────────────────────────────────────
    roleLabel: '使用者群組',
    rolePlaceholder: '— 選擇使用者群組 —',
    userLabel: '使用者',
    saveChanges: '儲存變更',
    discard: '放棄',
    cancel: '取消',
    apply: '套用',
    close: '關閉',
    inherit: '繼承',
    allow: '允許',
    deny: '拒絕',
    umbracoUsers: '所有使用者',

    // ── 權限編輯器 ───────────────────────────────────────────────────────
    editorHeadline: '內容權限編輯器',
    selectRolePrompt: '請在上方選擇使用者群組以管理其權限。',
    permissionsSaved: '權限已儲存。',
    saveFailed: (error: string) => `儲存失敗：${error}`,
    contentNodeHeader: '內容節點',
    contentRoot: '預設權限',
    expand: '展開',
    collapse: '收合',

    // ── 權限對話框 ─────────────────────────────────────────────────────────
    dialogHeadline: (verb: string, nodeName: string) => `為「${nodeName}」設定「${verb}」權限`,
    descendantsSection: '子孫節點（若不同）',
    dialogInstructions: '為此節點設定權限。預設情況下，此設定也會套用至所有子孫節點。使用「子孫節點（若不同）」可為子孫節點設定不同的權限。',
    virtualRootInherit: '未設定（移除項目）',
    virtualRootAllow: '允許（所有內容）',
    virtualRootDeny: '拒絕（所有內容）',
    dialogResult: '結果',
    previewBothInherit: '未設定權限。從父節點繼承。',
    previewUniform: (action: string) => `對此節點及所有子孫節點${action}。`,
    previewNodeOnly: (action: string) => `僅對此節點${action}。子孫節點不受此規則影響。`,
    previewDescOnly: (action: string) => `此節點沒有明確的權限。對所有子孫節點${action}。`,
    previewSplit: (nodeAction: string, descAction: string) => `對此節點${nodeAction}。對所有子孫節點${descAction}。`,
    previewVirtualInherit: '未設定預設權限。',
    previewVirtualSet: (action: string) => `對所有內容預設${action}。`,
    previewPriorityNode: '此節點已設定優先權覆寫。',
    previewPriorityDesc: '子孫節點已設定優先權覆寫。',
    previewPriorityBoth: '已設定優先權覆寫。',

    // ── 優先權覆寫 ────────────────────────────────────────────────────
    priorityOverride: '優先權覆寫',
    priorityOverrideTooltip: (permission: string, nodeName: string) =>
      `一位使用者可以同時屬於多個使用者群組。一般情況下，有效權限會依照固定的優先順序決定。勾選此選項會覆寫該順序，使您在此選擇的「${permission}」設定幾乎總是成為「${nodeName}」的結果，而不論該使用者所屬的其他群組為何。請謹慎使用。`,
    priorityOverrideBadgeTitle: '此項目已設定優先權覆寫',
    priorityOverrideWonTitle: '透過優先權覆寫解析',
    priorityOverrideSuppressedHeader: '優先權覆寫已變更結果',
    priorityOverrideSuppressedHint: '若未使用，結果原本會是：',

    // ── 存取檢視器 ─────────────────────────────────────────────────────────
    viewerHeadline: '內容存取檢視器',
    byRole: '依使用者群組',
    byUser: '依使用者',
    chooseRole: '選擇使用者群組',
    chooseUser: '選擇使用者',
    selectSubjectPrompt: '選擇使用者群組或使用者以檢視有效權限。',
    legendAllow: '允許',
    legendDeny: '拒絕',
    clickForReasoning: (label: string) => `${label} — 點選以檢視原因`,
    subjectOr: '或',

    // ── 使用者群組選擇器對話框 ──────────────────────────────────────────────
    rolePickerHeadline: '選擇使用者群組',
    rolePickerFilter: '輸入以篩選…',
    rolePickerNoResults: '沒有符合篩選條件的使用者群組。',
    rolePickerNameHeader: '使用者群組',

    // ── 使用者選擇器對話框 ──────────────────────────────────────────────────
    userPickerHeadline: '選擇使用者',
    userPickerFilter: '輸入以篩選…',
    userPickerNoResults: '沒有符合篩選條件的使用者。',
    userPickerNameHeader: '使用者',

    // ── 原因對話框 ────────────────────────────────────────────────────────
    reasoningHeadline: (verb: string, nodeName: string) => `「${nodeName}」的「${verb}」權限`,
    effectiveAllowed: (subject: string, verb: string, nodeName: string) =>
      `${subject}對「${nodeName}」已被允許「${verb}」權限。`,
    effectiveDenied: (subject: string, verb: string, nodeName: string) =>
      `${subject}對「${nodeName}」已被拒絕「${verb}」權限。`,
    dialogSecurityHeader: '安全性',
    defaultPermissions: '預設權限',
    determiningEntry: '此項目具有優先權',
    noReasoningData: '此動作沒有可用的權限資料。',
    defaultAllowNote: '未設定任何權限，此項預設為允許。',
    defaultDenyNote: '未設定任何權限，此項預設為拒絕。',

    // ── 細部權限重新導向 ──────────────────────────────────────────────────
    redirectMessage:
      '此使用者群組的文件權限由 Advanced Permissions 套件管理。請在「使用者」區段中開啟「內容權限編輯器」以設定權限。',

    // ── 文檔類型權限 ──────────────────────────────────────────────────────
    role: '使用者群組',
    pickRole: '選擇使用者群組',
    user: '使用者',
    pickUser: '選擇使用者',
    node: '節點',
    pickNode: '選擇節點',
    state: '狀態',
    scope: '範圍',
    scope_thisNodeOnly: '僅此節點',
    scope_thisNodeAndDescendants: '此節點及子孫節點',
    scope_descendantsOnly: '僅子孫節點',

    docTypePermissions_menuLabel: '文檔類型權限編輯器',
    docTypePermissions_insertOptionsMenuLabel: '插入選項檢視器',
    docTypePermissions_workspaceTitle: '文檔類型權限編輯器',
    docTypePermissions_auditTitle: '文檔類型存取檢視器',
    docTypePermissions_allDocTypes: '所有文檔類型',
    docTypePermissions_verbInsert: '插入',
    docTypePermissions_documentType: '文檔類型',
    chooseDocType: '選擇文檔類型',
    notAnInsertOption: '此文檔類型目前不是此節點的插入選項。',
    notAnInsertOptionAllowedNote: '此文檔類型不是此節點的插入選項，但若是的話會被允許。',
    notAnInsertOptionDeniedNote: '此文檔類型不是此節點的插入選項，但若是的話會被拒絕。',
    docTypePermissions_pickDocType: '— 選擇文檔類型 —',
    docTypePermissions_pickToStart: '選擇使用者群組與文檔類型以開始。',
    docTypePermissions_defaultRowLabel: '預設（套用至各處）',
    docTypePermissions_pendingNodeLabel: '（未儲存的節點）',
    docTypePermissions_addScopeNode: '新增範圍覆寫',
    docTypePermissions_notSet: '未設定',
    docTypePermissions_noResults: '找不到文檔類型。',
    docTypePermissions_useRoot: '使用根節點',
    docTypePermissions_pickedNode: '節點：',
    docTypePermissions_rootLevel: '根層級',
    docTypePermissions_reasoning: '原因',
    docTypePermissions_defaultAllow: '預設允許',
    docTypePermissions_viaDefault: '來自預設列',
    // -- i18n completion (machine-translated, pending review) --
    help_contentPermissions_description: '依使用者群組管理整個內容樹狀結構的允許/拒絕權限。',
    help_accessViewer_description: '檢視使用者或群組在任一節點上的有效權限，並提供完整原因說明。',
    help_docTypePermissions_description: '決定每個使用者群組可以建立哪些文檔類型，以及可在何處建立。',
    help_insertOptions_description: '稽核使用者或使用者群組在每個節點上可建立哪些文檔類型。',
    help_libraryPermissions_description: '依使用者群組管理整個 Library 樹狀結構的允許/拒絕權限。',
    help_elementTypePermissions_description: '控制每個使用者群組可以在 Library 中使用哪些元素類型。',
    help_libraryAccessViewer_description: '檢視使用者或使用者群組在每個節點上的有效 Library 權限。',
    help_libraryInsertViewer_description: '稽核使用者或使用者群組在 Library 中可插入哪些元素類型。',
    help_learnMore: '了解更多',
    help_modalTitle: '說明',
    help_tabAbout: '關於此頁面',
    help_tabConcepts: '概念',
    help_concept_scope_tip: '範圍控制規則的適用範圍：僅此節點、此節點及其子孫節點，或僅子孫節點。',
    help_concept_priorityOverride_tip: '優先權覆寫會強制此項目勝過正常的解析順序。',
    help_concept_allowDeny_tip: '允許會授予權限，拒絕會撤銷權限，而保持未設定則會從最近的上層節點繼承。',
    help_concept_reasoning_tip: '點選任一儲存格即可確切了解權限是如何解析出來的。',
    previewElementFolderSet: (action: string) => `不適用於此資料夾。對其中的元素${action}。`,
    previewElementFolderInherit: '不適用於此資料夾。其中的元素會從其父節點繼承。',
    dialogElementFolderNote: (verb: string) => `「${verb}」不適用於資料夾——僅適用於其中的元素。`,
    elementFolderDescSection: '其中的元素',
    naChip: '不適用',
    redirectMessageElement:
      '此使用者群組的 Library（元素）權限由 Advanced Permissions 套件管理。請在「使用者」區段中開啟「Library 權限編輯器」以設定權限。',
    library_menuLabel: 'Library 權限編輯器',
    library_editorHeadline: 'Library 權限編輯器',
    library_accessViewerMenuLabel: 'Library 存取檢視器',
    library_accessViewerHeadline: 'Library 存取檢視器',
    library_nodeHeader: 'Library 項目',
    library_root: '預設權限',
    library_selectRolePrompt: '選擇使用者群組以管理其 Library 權限。',
    library_permissionsSaved: 'Library 權限已儲存。',
    library_notApplicableTitle: (verb: string) => `${verb}不適用於資料夾——但仍可為其中的項目設定。`,
    library_folderInheritLabel: '其中的項目（子孫節點）',
    libraryInsertViewer_menuLabel: 'Library 插入檢視器',
    libraryInsertViewer_headline: 'Library 元素類型存取檢視器',
    libraryInsertViewer_intro: '顯示使用者群組或使用者可建立哪些 Library 元素類型，並跨其所屬的所有群組進行解析。點選列即可檢視原因。',
    elementTypePermissions_menuLabel: 'Library 元素類型權限',
    elementTypePermissions_headline: 'Library 元素類型權限編輯器',
    elementTypePermissions_intro: '控制每個使用者群組可以在 Library 中建立哪些元素類型。元素類型預設可建立；設定允許或拒絕——並可選擇性地搭配優先權覆寫——以控制當使用者同時屬於多個群組時如何解析此選擇。',
    elementTypePermissions_typeHeader: '元素類型',
    elementTypePermissions_verbCreate: '在 Library 中建立',
    elementTypePermissions_noTypes: '找不到 Library 元素類型。請將文檔類型標記為元素類型並啟用「允許在 Library 中使用」。',
    elementType_dialogHeadline: (type: string) => `在 Library 中「${type}」的建立權限`,
    elementType_inheritLabel: '未設定（預設允許）',
    elementType_allowLabel: '允許（可在 Library 中建立）',
    elementType_denyLabel: '拒絕（從 Library 中隱藏）',
    elementType_previewInherit: '沒有明確的規則。此元素類型預設可在 Library 中建立。',
    elementType_previewSet: (action: string) => `${action}在 Library 中建立此元素類型。`,
  },
} satisfies UmbLocalizationDictionary;
