// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmbracoAdvancedSecurity.Data.Context;

#nullable disable

namespace UmbracoAdvancedSecurity.Data.Migrations.SqlServer
{
    [DbContext(typeof(AdvancedSecurityDbContextSqlServer))]
    partial class AdvancedSecurityDbContextSqlServerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UmbracoAdvancedSecurity.Data.Entities.AdvancedPermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("NodeKey")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NodeKey");

                    b.Property<string>("RoleAlias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RoleAlias");

                    b.Property<int>("Scope")
                        .HasColumnType("int")
                        .HasColumnName("Scope");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("State");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Verb");

                    b.HasKey("Id");

                    b.HasIndex("NodeKey")
                        .HasDatabaseName("IX_AdvancedSecurityPermission_NodeKey");

                    b.HasIndex("RoleAlias")
                        .HasDatabaseName("IX_AdvancedSecurityPermission_RoleAlias");

                    b.HasIndex("NodeKey", "RoleAlias")
                        .HasDatabaseName("IX_AdvancedSecurityPermission_NodeKey_RoleAlias");

                    b.HasIndex("NodeKey", "RoleAlias", "Verb", "Scope")
                        .IsUnique()
                        .HasDatabaseName("IX_AdvancedSecurityPermission_Unique")
                        .HasFilter("[NodeKey] IS NOT NULL");

                    b.ToTable("AdvancedSecurityPermission", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
