namespace Umbraco.Community.AdvancedPermissions.Core.Models;

/// <summary>
/// Represents a single stored document-type permission entry.
/// </summary>
/// <remarks>
/// <para>
/// Unlike <see cref="AdvancedPermissionEntry"/> (which is node-scoped), a doc-type entry is
/// keyed on both <c>NodeKey</c> and <c>ContentTypeKey</c>. It answers a different question:
/// "may this role create/affect documents of this type, under this subtree?".
/// </para>
/// <para>
/// The shared <see cref="Services.ResolutionEngine"/> resolves these entries using the same
/// path-walking + scope-precedence algorithm as node-level permissions, but with a default
/// state of Allow rather than Deny.
/// </para>
/// </remarks>
/// <param name="Id">The unique identifier for this entry (GUID, generated by the application).</param>
/// <param name="NodeKey">
/// The content-tree node the entry is scoped to. Use
/// <c>AdvancedPermissionsConstants.VirtualRootNodeKey</c> for the virtual-root row that
/// applies everywhere by default.
/// </param>
/// <param name="ContentTypeKey">
/// The document-type key this entry concerns. Combined with <see cref="Verb"/>, this is the
/// match dimension that distinguishes doc-type entries from node-level entries.
/// </param>
/// <param name="RoleAlias">
/// The role alias (user group alias or <c>$everyone</c>).
/// </param>
/// <param name="Verb">
/// The doc-type verb. v1 ships only <c>Umb.Document.CreateOfType</c>; the column exists so
/// future of-type verbs can join without schema work.
/// </param>
/// <param name="State">Whether this entry allows or denies the verb for the matched type/role.</param>
/// <param name="Scope">The scope at which this entry takes effect within the tree.</param>
public sealed record DocTypePermissionEntry(
    Guid Id,
    Guid NodeKey,
    Guid ContentTypeKey,
    string RoleAlias,
    string Verb,
    PermissionState State,
    PermissionScope Scope);
