// <auto-generated />
using System;
using LP.Umbraco.AdvancedPermissions.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LP.Umbraco.AdvancedPermissions.Data.Migrations.Sqlite
{
    [DbContext(typeof(AdvancedPermissionsDbContextSqlite))]
    [Migration("20260405195528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("LP.Umbraco.AdvancedPermissions.Data.Entities.AdvancedPermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid?>("NodeKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("NodeKey");

                    b.Property<string>("RoleAlias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("RoleAlias");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Scope");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Verb");

                    b.HasKey("Id");

                    b.HasIndex("NodeKey")
                        .HasDatabaseName("IX_AdvancedPermission_NodeKey");

                    b.HasIndex("RoleAlias")
                        .HasDatabaseName("IX_AdvancedPermission_RoleAlias");

                    b.HasIndex("NodeKey", "RoleAlias")
                        .HasDatabaseName("IX_AdvancedPermission_NodeKey_RoleAlias");

                    b.HasIndex("NodeKey", "RoleAlias", "Verb", "Scope")
                        .IsUnique()
                        .HasDatabaseName("IX_AdvancedPermission_Unique");

                    b.ToTable("AdvancedPermission", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
