using Umbraco.Community.AdvancedPermissions.Core.Models;

namespace Umbraco.Community.AdvancedPermissions.Data.Entities;

/// <summary>
/// EF Core entity for the <c>DocTypePermission</c> table — document-type-scoped permission
/// entries that the doc-type resolver consumes alongside (but separately from) the node-level
/// <see cref="AdvancedPermissionEntity"/> entries.
/// </summary>
public sealed class DocTypePermissionEntity
{
    /// <summary>
    /// Gets or sets the primary key (GUID, generated by the application).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the key of the node this entry is scoped to.
    /// Use <c>AdvancedPermissionsConstants.VirtualRootNodeKey</c> for the virtual-root row.
    /// </summary>
    public Guid NodeKey { get; set; }

    /// <summary>
    /// Gets or sets the doc-type key this entry concerns. Combined with <see cref="Verb"/>, this is
    /// the dimension that distinguishes a doc-type entry from a node-level permission entry.
    /// </summary>
    public Guid ContentTypeKey { get; set; }

    /// <summary>
    /// Gets or sets the role alias (user group alias or <c>$everyone</c>).
    /// </summary>
    public string RoleAlias { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the doc-type verb. v1 ships <c>Umb.Document.CreateOfType</c> only; the column
    /// exists so future of-type verbs can join without schema work.
    /// </summary>
    public string Verb { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the permission state (Allow or Deny).
    /// </summary>
    public PermissionState State { get; set; }

    /// <summary>
    /// Gets or sets the scope at which this entry applies within the content tree.
    /// </summary>
    public PermissionScope Scope { get; set; }
}
