using Umbraco.Community.AdvancedPermissions.Core.Models;

namespace Umbraco.Community.AdvancedPermissions.Data.Entities;

/// <summary>
/// Common shape of a node-keyed permission entity. Implemented by every node-based permission table
/// entity (<see cref="AdvancedPermissionEntity"/> for content, <see cref="ElementPermissionEntity"/>
/// for library elements/folders) so a single generic repository base can read and write them.
/// </summary>
/// <remarks>
/// All members are mapped to identically-named columns across the implementing entities, which lets
/// <c>NodePermissionRepositoryBase&lt;TEntity&gt;</c> translate predicates over this interface against
/// each concrete table via <c>DbSet&lt;TEntity&gt;</c>.
/// </remarks>
public interface INodePermissionEntity
{
    /// <summary>Gets or sets the primary key (GUID, generated by the application).</summary>
    Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the key of the node this entry applies to. Use
    /// <c>AdvancedPermissionsConstants.VirtualRootNodeKey</c> for virtual-root (default) entries.
    /// </summary>
    Guid NodeKey { get; set; }

    /// <summary>Gets or sets the role alias (a user group alias or <c>$everyone</c>).</summary>
    string RoleAlias { get; set; }

    /// <summary>Gets or sets the permission verb, e.g. <c>Umb.Document.Read</c> or <c>Umb.Element.Read</c>.</summary>
    string Verb { get; set; }

    /// <summary>Gets or sets the permission state (Allow or Deny).</summary>
    PermissionState State { get; set; }

    /// <summary>Gets or sets the scope at which this entry applies within the tree.</summary>
    PermissionScope Scope { get; set; }

    /// <summary>Gets or sets the priority-override flag (CSS <c>!important</c>-style cross-role tie-breaker).</summary>
    bool IsPriorityOverride { get; set; }
}
