// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmbracoAdvancedSecurity.Data.Context;

#nullable disable

namespace UmbracoAdvancedSecurity.Data.Migrations.Sqlite
{
    [DbContext(typeof(AdvancedSecurityDbContextSqlite))]
    partial class AdvancedSecurityDbContextSqliteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("UmbracoAdvancedSecurity.Data.Entities.AdvancedPermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid?>("NodeKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("NodeKey");

                    b.Property<string>("RoleAlias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("RoleAlias");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Scope");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Verb");

                    b.HasKey("Id");

                    b.HasIndex("NodeKey")
                        .HasDatabaseName("IX_AdvancedSecurityPermission_NodeKey");

                    b.HasIndex("RoleAlias")
                        .HasDatabaseName("IX_AdvancedSecurityPermission_RoleAlias");

                    b.HasIndex("NodeKey", "RoleAlias")
                        .HasDatabaseName("IX_AdvancedSecurityPermission_NodeKey_RoleAlias");

                    b.ToTable("AdvancedSecurityPermission", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
