namespace Umbraco.Community.AdvancedPermissions.Core.Models;

/// <summary>
/// Represents a single stored permission entry in the advanced security system.
/// An entry defines the state (Allow/Deny) and scope for a specific role and permission verb
/// on a specific content node.
/// </summary>
/// <param name="Id">The unique identifier for this entry (GUID, generated by the application on creation).</param>
/// <param name="NodeKey">
/// The key of the content node this entry applies to.
/// Use <c>AdvancedPermissionsConstants.VirtualRootNodeKey</c> for virtual-root (default) entries that affect all nodes.
/// </param>
/// <param name="RoleAlias">
/// The alias of the role (user group alias or <c>$everyone</c> for the virtual Everyone role).
/// </param>
/// <param name="Verb">The permission verb, e.g. <c>Umb.Document.Read</c>.</param>
/// <param name="State">Whether this entry allows or denies the permission.</param>
/// <param name="Scope">The scope at which this entry takes effect within the tree.</param>
/// <param name="IsPriorityOverride">
/// When <see langword="true"/> on an entry that applies at the target node itself (depth 0),
/// the resolver switches into a "consider only priority-override entries on this node, for this
/// verb" mode — modelled after CSS <c>!important</c>. The flag has node-local, verb-local effect
/// only: it does not propagate through inheritance, and it has no effect at any other node or for
/// any other verb. Its purpose is to provide an escape hatch for the otherwise-unoverridable
/// cross-role Explicit Deny when a user belongs to multiple user groups.
/// </param>
public sealed record AdvancedPermissionEntry(
    Guid Id,
    Guid NodeKey,
    string RoleAlias,
    string Verb,
    PermissionState State,
    PermissionScope Scope,
    bool IsPriorityOverride = false);
